from __future__ import annotations

from typing import Any

VERSION_NOTES: dict[str, dict[str, Any]] = {
    "1.8.0": {
        "title": "TNC KISS, Digipeater, iGate e otimização inteligente de RF",
        "items": [
            "Inicia a série 1.8 com uma nova aba TNC / RF para operação local de rádio além do APRS-IS.",
            "Adiciona KISS TCP e KISS Serial, listagem de portas, reconexão, monitor de frames AX.25/APRS e contadores RX/TX.",
            "Implementa decodificação e geração AX.25 UI, KISS escaping, representação TNC2 e suporte a paths com SSID e indicador de repetição.",
            "Adiciona Digipeater com perfis Fill-in WIDE1-1, Wide/Regional WIDEn-N e aliases personalizados, com supressão de duplicatas, prevenção de loops, limite de hops e rate limit por origem.",
            "Adiciona fila de TX com prioridade para ACK/REJ e mensagens, mantendo telemetria e tráfego de baixa prioridade atrás do tráfego útil.",
            "Adiciona iGate RF→APRS-IS com qAR e iGate APRS-IS→RF restritivo a mensagens destinadas a estações ouvidas diretamente por RF dentro da janela configurada.",
            "Constrói grafo de quem fala com quem usando mensagens e ACK/REJ observados em RF e APRS-IS, com recomendações e modo automático conservador.",
            "Registra frames, estações ouvidas, decisões de digi/iGate e relações de comunicação no SQLite local com retenção configurável.",
            "TX automático, Digipeater e iGate Internet→RF permanecem desligados por padrão e exigem confirmação explícita; há botão PARAR TX para bloqueio imediato sem derrubar RX.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.7.23": {
        "title": "Produção: relevo com corte, hillshade e novos mapas-base",
        "items": [
            "Adiciona Mapa → Camadas → Relevo com corte, usando DEM Terrarium real para mostrar somente terreno igual ou acima da cota selecionada.",
            "O corte é ajustado em tempo real por slider vertical no lado direito do mapa, com cota atual visível e limite máximo padrão de 3.000 m configurável até 9.000 m.",
            "Adiciona controle independente de opacidade do Relevo com corte e persiste cota, máximo do slider e transparência no banco local.",
            "Adiciona Relevo sombreado como camada independente usando Esri World Hillshade, sem acionar o slider de corte.",
            "Adiciona os mapas-base Claro (CARTO Positron) e Escuro (CARTO Dark Matter), mantendo OSM, Topográfico e Satélite.",
            "Mantém Clima/RainViewer independente dos mapas-base e não inclui camada de raios.",
            "Estações APRS, objetos, tracklogs, enlaces, replay e animações permanecem acima das camadas de relevo.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.7.22": {
        "title": "Produção: camada de clima, radar e popup protegido",
        "items": [
            "Adiciona Mapa → Camadas → Clima, com radar de precipitação mais recente disponível no RainViewer sobre qualquer mapa-base.",
            "A camada de clima fica desligada por padrão e pode ser ligada ou desligada independentemente de OSM, Topográfico ou Satélite.",
            "Configuração ganha controle de opacidade do radar, aplicado imediatamente e persistido no banco com migração automática.",
            "O radar é atualizado periodicamente enquanto a camada está ativa e mantém a última imagem válida se uma atualização temporariamente falhar.",
            "O popup de estação passa a usar altura máxima, rolagem interna, keepInView e margem superior de auto-pan para reduzir cortes sob a barra do mapa.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.7.21": {
        "title": "Hover detalhado de enlaces e tracklogs; atualização sem acúmulo",
        "items": [
            "No Mapa, passar o mouse sobre um enlace mostra um painel fixo com origem, destino, tipo RF ou Internet/APRS-IS, sentido, pacotes, primeira/última observação e iGate quando disponível.",
            "Passar o mouse sobre um tracklog mostra início, fim, duração, distância, velocidade média e máxima, posições, coordenadas inicial/final, digipeaters, iGates, caminhos APRS, RSSI/SNR quando disponíveis e período do mapa.",
            "Novos pontos de tracklog passam a persistir path, pacote bruto, RSSI e SNR quando recebidos; históricos antigos continuam compatíveis e exibem apenas os dados que já existiam.",
            "O updater reutiliza sempre o nome oficial do pacote e sobrescreve downloads anteriores, sem gerar cópias numeradas.",
            "Após uma versão iniciar com sucesso, pacotes antigos e downloads parciais são removidos da pasta temporária, preservando somente uma atualização realmente mais nova ainda pendente.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.7.20": {
        "title": "Produção: período das Estatísticas, RF × Internet e primeira configuração",
        "items": [
            "Corrige o filtro por período da aba Estatísticas, que passa a usar sua própria seleção e não mais o período do Mapa.",
            "Mapa e Estatísticas mantêm períodos independentes e persistidos separadamente.",
            "A classificação de topologia preserva qAR/qAO como evidência de recepção direta por RF, inclusive quando TCPIP/TCPXX aparece em outra parte do path; qAr permanece Internet/APRS-IS.",
            "Na primeira execução ou quando a configuração obrigatória estiver incompleta, o aplicativo abre diretamente em Configuração e posiciona o foco no Indicativo.",
            "A página principal do GitHub remove a tabela de contadores de downloads e oferece links diretos para os produtos da Release latest.",
            "O workflow automático que recriava a tabela de contadores de downloads foi desativado no branch principal.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF, publicada como GitHub Release latest após validação integral.",
        ],
    },
    "1.7.19": {
        "title": "Produção: mapa por famílias, estatísticas consolidadas e RF observado",
        "items": [
            "Objetos APRS passam a ser classificados pela semântica do próprio objeto, sem herdar o software/TOCALL da estação publicadora.",
            "A árvore Ver mantém grupos principais mutuamente exclusivos para estações, digipeaters, iGates e objetos.",
            "Estatísticas consolidam atividade e interações em uma única tabela ordenável de estações comuns.",
            "Digipeaters e iGates são excluídos do ranking de estações também pela classificação APRS Device ID, não apenas pela topologia observada.",
            "O ranking mostra indicativo, pacotes úteis, interações, enviadas, recebidas, contatos, última atividade e tipo/aplicação.",
            "O popup da estação mostra as estações comprovadamente recebidas por RF, com quantidade de pacotes e última observação.",
            "Mantém a árvore Ver por famílias, seleção parcial corrigida, flags de idioma e demais correções das versões de validação 1.7.16-1.7.18.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF, publicada como GitHub Release latest após validação integral.",
        ],
    },
    "1.7.18": {
        "title": "Validação Windows x64: seleção parcial do menu Ver",
        "items": [
            "Corrige o caso em que famílias marcadas em Objetos APRS não apareciam no mapa quando o pai estava em estado intermediário.",
            "O estado do grupo pai passa a ser derivado dos filhos: qualquer filho ativo mantém o grupo habilitado.",
            "Pai parcialmente selecionado representa seleção parcial, não grupo desligado.",
            "A mesma regra vale para Estações, Digipeaters, iGates e Objetos APRS.",
            "Marcar o pai ativa todos os filhos; desmarcar o pai desativa todos; marcar apenas algumas famílias mostra somente essas famílias.",
            "Build de validação somente para Windows x64 Portable, destinado ao teste da seleção parcial do menu Ver.",
        ],
    },
    "1.7.17": {
        "title": "Validação Windows x64: filtros Ver por tipo/família",
        "items": [
            "Remove indicativos e objetos individuais da árvore Ver como níveis de filtragem.",
            "Objetos APRS passam a ser agrupados por família funcional, como RDZSonDe, em vez de por indicativo de origem.",
            "Estações, digipeaters e iGates passam a ser agrupados diretamente por produto/tipo, como Bravo Tracker, DMR, D-Star, HBLink, Dire Wolf e Aprx.",
            "Desmarcar uma família oculta todos os itens daquele tipo no mapa, independentemente do indicativo.",
            "A contagem ao lado da família representa quantos itens daquele tipo estão no período atual do mapa.",
            "Filtros antigos da v1.7.16 são migrados para uma nova chave para evitar ocultações indevidas.",
            "Build de validação somente para Windows x64 Portable, destinado ao teste do agrupamento por famílias.",
        ],
    },
    "1.7.16": {
        "title": "Validação Windows x64: menu Ver hierárquico no Mapa",
        "items": [
            "Substitui Itens do mapa por Ver, com árvore expansível inspirada no filtro de camadas do Google Earth.",
            "Separa Estações, Digipeaters, iGates, Objetos APRS, Tracklogs, enlaces RF, enlaces iGate/APRS-IS e pacotes em movimento.",
            "Estações são subdivididas por classe APRS, fabricante e modelo usando o snapshot offline aprs-deviceid já incluído no aplicativo.",
            "Digipeaters e iGates recebem subdivisões por APRS convencional, LoRa APRS, híbridos Digi+iGate e itens não identificados.",
            "Objetos APRS podem ser expandidos por origem e individualmente ligados/desligados.",
            "Filtros persistem entre execuções e também afetam tracklogs, topologia e animação de pacotes.",
            "Tudo permanece ligado por padrão.",
            "Build de validação somente para Windows x64 Portable, destinado ao teste da nova árvore Ver.",
        ],
    },
    "1.7.15": {
        "title": "Produção: interações APRS inteligentes e Release latest",
        "items": [
            "Digipeaters, hotspots e outras estações de infraestrutura deixam mensagens e queries APRS desabilitadas quando não há evidência de capacidade interativa.",
            "Uma estação de infraestrutura volta a permitir interação automaticamente quando já enviou mensagem, respondeu ACK/REJ, enviou query ou respondeu uma query dirigida.",
            "Objetos e itens APRS permanecem não interativos.",
            "Ações passivas, como Ver logs e histórico de queries, continuam disponíveis.",
            "Mantém a checagem de atualização ao iniciar e a cada 30 minutos.",
            "Status de atualização permanece como Versão atualizada ou Versão X.X.X disponível em laranja e piscando.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF, publicada como GitHub Release latest.",
        ],
    },
    "1.7.13": {
        "title": "Validação Windows x64: símbolos APRS, animação limpa e status de versão",
        "items": [
            "Objetos APRS passam a usar o símbolo real recebido no pacote; fallback só é usado quando o símbolo não existe.",
            "Remove o rótulo branco APRS-IS da animação, mantendo somente halo e destaque visual.",
            "O destaque de transmissão cresce e volta ao normal em aproximadamente 1 segundo.",
            "Na barra superior, versão atual mostra Versão atualizada.",
            "Quando há atualização, mostra Versão X.X.X disponível em laranja e piscando.",
            "A checagem automática de nova versão permanece a cada 30 minutos.",
            "Build de validação somente para Windows x64 Portable, destinado à validação dos ajustes recentes.",
        ],
    },
    "1.7.12": {
        "title": "Validação Windows x64: todos os marcadores clicáveis no mapa",
        "items": [
            "Cria panes separados no Leaflet para marcadores clicáveis e camadas visuais.",
            "Estações, objetos APRS e marcadores de consulta ficam em pane superior com eventos habilitados.",
            "Tracklogs, topologia, halos e pacotes animados ficam em pane inferior sem pointer-events.",
            "Reforça cursor e área clicável dos ícones de estação e objetos APRS.",
            "Build de validação somente para Windows x64 Portable.",
        ],
    },
    "1.7.11": {
        "title": "Validação Windows x64: correção do menu Itens do mapa",
        "items": [
            "Corrige o menu Itens do mapa que ficava recortado pela barra superior.",
            "O dropdown passa a ser posicionado como camada fixa abaixo do botão, fora do overflow da barra.",
            "Mantém abertura/fechamento por clique, fechamento ao clicar fora e reposicionamento em scroll/resize.",
            "Build de validação somente para Windows x64 Portable.",
        ],
    },
    "1.7.10": {
        "title": "Validação Windows x64: mapa unificado, APRS-IS animado e cliques restaurados",
        "items": [
            "A barra do Mapa passa a ter um único período para estações, objetos, tracklogs, enlaces e replay.",
            "Itens do mapa reúne toggles para estações, objetos, tracklogs, enlaces RF, enlaces iGate/APRS-IS e pacotes em movimento, todos ligados por padrão.",
            "O tipo de mapa pode ser trocado diretamente entre OSM, Topográfico e Satélite.",
            "A entrega do pacote ao APRS-IS é animada no próprio iGate, sem inventar uma coordenada geográfica para a Internet.",
            "Camadas de animação, tracklog e topologia deixam de capturar cliques, preservando a interação com estações e objetos.",
            "Build de validação somente para Windows x64 Portable.",
        ],
    },
    "1.7.9": {
        "title": "Validação Windows x64: velocidade da animação no Mapa e rótulo Versão",
        "items": [
            "Na barra contextual do Mapa, o controle Velocidade passa a ficar entre Topologia observada e o seletor de período.",
            "As opções de velocidade são 0,5x, 1x, 2x e 5x, com 1x como padrão.",
            "O seletor da barra do Mapa e o seletor do Replay permanecem sincronizados e controlam a mesma velocidade de animação.",
            "A velocidade escolhida fica persistida localmente para a próxima abertura.",
            "Na barra superior, o texto Build passa a ser exibido como Versão em português.",
            "Build de validação somente para Windows x64 Portable, destinado à validação dos ajustes recentes.",
        ],
    },
    "1.7.8": {
        "title": "Validação Windows x64: tráfego APRS hop a hop e ACK pelo path observado",
        "items": [
            "A animação de tráfego passa a percorrer os segmentos observados sequencialmente, hop a hop.",
            "Cada hop ativa visualmente a estação de destino quando o pacote chega ao nó.",
            "Enlaces RF permanecem distintos dos trechos APRS-IS/Internet, que continuam com representação própria.",
            "ACK/REJ e respostas correlacionadas usam o path observado no pacote de retorno; quando os mesmos digipeaters são usados, a animação volta pelo mesmo caminho em sentido inverso.",
            "Não é criado enlace direto artificial entre origem e destino quando existem hops observados.",
            "Respostas automáticas a queries APRS ficam ativadas por padrão em novas configurações.",
            "Build de validação solicitado somente para Windows x64 Portable, sem instalador e sem builds de outras plataformas.",
        ],
    },
    "1.7.7": {
        "title": "Mapa mais limpo, novos padrões visuais e checagem de atualização a cada 30 minutos",
        "items": [
            "O botão Histórico permanece somente na barra contextual do Mapa; o antigo botão global deixa de ser recriado pelo patch legado de build.",
            "Na aba Mensagens, a ação destrutiva passa a se chamar Limpar, mantendo destaque vermelho e confirmação antes da exclusão.",
            "A Topologia observada passa a usar amarelo (#ffff00) e espessura mínima de 1 px como padrão para novas configurações.",
            "O Tracklog permanece azul por padrão, e animações de atividade e som continuam ativados por padrão.",
            "A verificação periódica de nova versão passa de 5 para 30 minutos, sem sobrepor verificações ainda em andamento.",
            "Windows ARM64 passa a ter Setup e Portable nativos, e o atualizador escolhe automaticamente o pacote da arquitetura correta.",
            "A topologia passa a preservar a capitalização dos q-constructs APRS-IS, evitando interpretar qAr/links remotos de Internet como qAR/enlace RF.",
            "Preferências já personalizadas pelo usuário são preservadas; os novos valores visuais valem como padrão para instalações/configurações não personalizadas.",
            "Adicionados testes de regressão para evitar duplicação do Histórico, validar o botão Limpar, os padrões do Mapa e a nova cadência de atualização.",
            "Release completa para Windows x64 e ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.7.6": {
        "title": "Atualizador Windows reforçado, KML com Salvar como e novos rankings",
        "items": [
            "No Windows, a atualização automática passa a usar helper CMD nativo como caminho principal, reduzindo falhas de inicialização do PowerShell.",
            "O KML agora pergunta onde salvar o arquivo no desktop e usa seletor nativo de arquivo quando disponível.",
            "Os botões Histórico e Exportar KML foram movidos para a mesma barra contextual do Mapa, junto de Estações, Tracklog e Topologia.",
            "A aba Estatísticas ganha o ranking Estações que mais interagiram, considerando somente conversas APRS manuais e excluindo beacons, telemetria, ACK/REJ, queries, respostas automáticas, boletins e retries.",
            "A exportação KML continua com Estações, Posições, Tracklogs e Topologia selecionados por padrão e período configurável.",
            "Adicionados testes de regressão para o helper Windows, Salvar como do KML, posição dos controles no Mapa e ranking de conversas manuais.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.7.5": {
        "title": "Exportação KML, validação de posições e novas análises da rede",
        "items": [
            "Adicionada exportação KML pela barra superior, com Estações, Posições, Tracklogs e Topologia selecionados por padrão e período configurável.",
            "Posições 0,0, inválidas, saltos implausíveis e coordenadas incompatíveis com um iGate RF conhecido deixam de contaminar mapa, tracklogs, topologia, replay e exportações.",
            "A aba Estatísticas ganha os blocos Estações com problemas e Possíveis melhorias, com evidência/recorrência e atalhos para Mapa e Logs.",
            "Indicativos dos rankings Digipeaters mais utilizados e iGates mais ativos passam a abrir diretamente a estação no Mapa.",
            "Conversas da aba Mensagens podem ser ordenadas por Remetente ou Data, em ordem crescente/decrescente, e a ação Apagar todas remove somente o histórico local de mensagens após confirmação.",
            "Adicionados testes de regressão para validação geográfica, KML, navegação das Estatísticas e controles de Mensagens.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.7.4": {
        "title": "Erros do atualizador agora ficam visíveis no próprio modal",
        "items": [
            "Corrigida a camada visual das mensagens do atualizador: o toast agora fica acima do modal e não é mais desfocado pelo overlay.",
            "Falhas de download/instalação passam a ser exibidas também dentro do modal de atualização, em uma caixa destacada e legível.",
            "O estado do modal distingue claramente preparação, sucesso e erro, mantendo os botões disponíveis após uma falha.",
            "A mensagem técnica do backend permanece visível para diagnóstico, sem depender de um aviso temporário.",
            "Adicionados testes de regressão para z-index, mensagem inline e reativação dos controles após erro.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.7.3": {
        "title": "Atualizador reparado e ranking de clientes consolidado por família",
        "items": [
            "Corrigida a geração dos scripts auxiliares do atualizador: as quebras de linha agora são gravadas corretamente em PowerShell e Bash.",
            "O botão Baixar e instalar mostra feedback imediato, dispara diretamente o fluxo de atualização e registra as etapas no diagnóstico.",
            "O updater registra solicitação, asset, URL, caminho temporário, tamanho, SHA-256 e falhas para facilitar diagnóstico.",
            "Estatísticas passa a agrupar versões semânticas do mesmo cliente em uma única família, por exemplo Dire Wolf 1.7, 1.8 e 1.9 em Dire Wolf.",
            "Aliases, nomes originais e TOCALLs continuam preservados internamente para diagnóstico, enquanto a interface mostra o nome canônico consolidado.",
            "Adicionados testes de regressão que geram os helpers reais e validam a consolidação por família.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.7.2": {
        "title": "Mapa mais compacto, tempo relativo e estatísticas consolidadas",
        "items": [
            "Estações, Tracklog e Topologia observada passam para a mesma linha contextual do botão Histórico, liberando mais área vertical para o mapa.",
            "O popup da estação mostra o tempo decorrido desde a última recepção e o atualiza enquanto permanece aberto.",
            "O tempo relativo respeita Português, English, Español e Français, com formatos compactos para minutos, horas e dias.",
            "O ranking de software/dispositivos consolida TOCALLs diferentes que resolvem para o mesmo nome amigável, evitando linhas duplicadas.",
            "Os identificadores técnicos continuam preservados internamente e o destaque do PT2VHF APRS Client é mantido após a consolidação.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.7.1": {
        "title": "Atualizador corrigido, Mapa refinado e nova aba Sobre",
        "items": [
            "O atualizador só encerra a aplicação depois que o helper externo confirma que iniciou; falhas deixam a aplicação aberta.",
            "O indicador de nova versão pulsa e o modal permanece aberto durante o fluxo de atualização.",
            "Tracklogs rejeitam saltos irreais de coordenadas e quebram linhas históricas em relocações/extremos.",
            "Estações, Tracklog e Topologia ganham controles independentes de visibilidade e período; Atividade é removido.",
            "Histórico/Replay passa a aparecer abaixo das abas somente quando o Mapa está ativo.",
            "Mensagens sinaliza novas mensagens diretas na aba e Estações mais ativas ganha atalho clicável para mensagem rápida.",
            "Nova aba Sobre reúne autor, contatos, tiny.cc/aprs e divulgação manual por Announcement APRS.",
            "Revisadas e ampliadas as traduções PT/EN/ES/FR.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.7": {
        "title": "Nova linha 1.7: mensagens seguras, idiomas e interface refinada",
        "items": [
            "Os controles Atividade e Topologia observada ficam acima do mapa, sem cobrir o canvas.",
            "A animação de tráfego ao vivo vem ativada por padrão em novas instalações e pode ser desligada em Configurações.",
            "A conversa em foco e o campo Destinatário ficam sincronizados para reduzir o risco de envio à estação errada.",
            "Os filtros da aba Mensagens ficam mais compactos e com rótulos em uma única linha.",
            "A interface passa a oferecer Português, English, Español e Français.",
            "Estatísticas mostra somente nomes amigáveis dos aplicativos e ganha fonte maior com controle de tamanho em Configurações.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.6.24": {
        "title": "Logo APRS oficial única e consolidação visual",
        "items": [
            "A logo APRS enviada pelo projeto passa a ser a fonte visual única da aplicação.",
            "Cabeçalho, favicon, bandeja do Windows, ícones Windows/Linux/macOS e capa do Manual PDF passam a derivar do mesmo arquivo PNG oficial.",
            "O ícone do macOS deixa de ser desenhado por código e passa a ser gerado diretamente da logo oficial.",
            "As notas internas da v1.6.23 são incorporadas para manter o histórico de novidades coerente.",
            "O backlog é consolidado, removendo itens já concluídos e mantendo abertas somente as validações e melhorias ainda pendentes.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.6.23": {
        "title": "Identidade visual, filtro de atividade e legenda do mapa",
        "items": [
            "Padroniza a identidade visual da aplicação nos artefatos e documentação existentes.",
            "Adiciona no Mapa filtro por última interação: Tudo, menos de 2 h, 2 a 24 h e mais de 24 h.",
            "Marcadores, tracklogs e enlaces de estações conhecidas respeitam o filtro de atividade.",
            "A legenda do Mapa pode ser minimizada ou expandida e preserva a preferência local.",
            "Corrige o rate-limit para permitir corretamente a primeira resposta automática a query APRS após a inicialização.",
            "Release completa multiplataforma.",
        ],
    },
    "1.6.22": {
        "title": "Atualização integrada por plataforma",
        "items": [
            "Clicar em Nova versão passa a baixar e instalar automaticamente o pacote correto da plataforma e arquitetura em uso.",
            "O download é feito somente da Release oficial e é validado por tamanho e SHA-256 antes da instalação.",
            "Um updater auxiliar encerra a instância anterior, força somente o PID correto após timeout quando necessário, instala/substitui e abre a nova versão.",
            "Windows Portable mantém backup para rollback; Windows Setup executa o instalador correspondente.",
            "Linux AppImage/DEB/TAR.GZ e macOS DMG recebem fluxos próprios de atualização e relançamento.",
            "Um lock com PID impede atualizações concorrentes entre instâncias e se recupera de locks obsoletos após crash.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.6.21": {
        "title": "Estatísticas da rede e ranking de estações ativas",
        "items": [
            "A aba Análise passa a se chamar Estatísticas em toda a interface e documentação.",
            "A nova seção Estações mais ativas ordena o tráfego útil por indicativo no período selecionado.",
            "Pacotes de telemetria são excluídos do ranking para evitar distorção por transmissões automáticas frequentes.",
            "iGates e digipeaters também são excluídos do ranking principal e permanecem nas estatísticas dedicadas.",
            "O ranking exibe posição, indicativo, pacotes válidos e percentual sobre o total considerado.",
            "Release de teste somente Windows x64 Portable.",
        ],
    },
    "1.6.20": {
        "title": "Nomes amigáveis APRS, ranking do cliente, idioma compacto e RF correto",
        "items": [
            "A aba Análise passa a resolver TOCALLs para nomes amigáveis de software/dispositivo usando um snapshot local da base APRS Device Identification.",
            "O ranking mostra os Top 20 e, se o PT2VHF APRS Client estiver fora do corte, acrescenta sua posição real, quantidade e percentual em uma linha destacada.",
            "O PT2VHF APRS Client passa a transmitir o identificador experimental APZVHF para permitir medir sua adoção sem depender do TOCALL genérico APRS.",
            "O seletor de idioma no topo passa a mostrar somente o idioma atual e abre um menu com Português/Brasil e English/Inglaterra.",
            "Corrige enlaces qAR/qAO até o IGate: quando o caminho é RF, a linha permanece contínua e o IGate fica apenas como metadado do enlace.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.6.19": {
        "title": "Análise de clientes, respostas de queries e idioma no topo",
        "items": [
            "A aba Análise passa a mostrar clientes/versões APRS detectados pelo TOCALL do último pacote de cada estação, em ordem do mais usado para o menos usado.",
            "O popup da estação passa a exibir uma área clara e persistente com o resultado da última query, incluindo status, RTT, resposta e caminho do Trace quando disponível.",
            "Adiciona histórico de queries por estação diretamente no popup do Mapa.",
            "Ao reabrir o popup, a última query registrada daquela estação é recuperada do banco local.",
            "Restaura o controle rápido de idioma no topo, com Português/Brasil e English/Inglaterra, preservando a escolha do usuário.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.6.18": {
        "title": "Queries APRS, Ping/ACK e Trace no mapa",
        "items": [
            "Adiciona consultas APRS direcionadas de posição, status, estações ouvidas e trace diretamente pelo popup do mapa.",
            "Adiciona Ping/ACK com medição de RTT e timeout.",
            "O Trace recebido é interpretado e desenhado no mapa somente nos hops com posição conhecida, sem inventar localização para nós desconhecidos.",
            "Adiciona histórico local das queries, respostas e tempos de resposta.",
            "Prepara o cliente para responder automaticamente a queries APRS de posição, status e trace, com opção em Configurações e rate-limit.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.6.17": {
        "title": "Release completa multiplataforma com correções de estabilidade",
        "items": [
            "Consolida as correções de CPU e travamento introduzidas nas versões 1.6.13 a 1.6.16.",
            "Mantém o pipeline RX otimizado, o refresh de mapa single-flight e a consulta de topologia indexada com proteção de timeout.",
            "Mantém os indicadores de CPU e RAM em tempo real na barra superior para diagnóstico operacional.",
            "Publica Windows x64 Setup + Portable, Linux x86_64 TAR.GZ/AppImage/DEB, macOS ARM64/Intel e Manual PDF versionado.",
            "O manual é regenerado com screenshots da própria versão e validado no workflow antes da publicação.",
        ],
    },
    "1.6.16": {
        "title": "Correção da consulta de topologia que saturava o backend",
        "items": [
            "Remove UPPER() dos JOINs de topologia para permitir lookup indexado pelo callsign.",
            "Impede consultas /api/topology concorrentes com coalescência/cache curto.",
            "Adiciona limite interno de tempo à consulta para que nenhum worker fique preso por minutos.",
            "Adiciona single-flight ao carregamento de topologia no frontend.",
            "Inclui índices auxiliares de topologia para bancos existentes e novos.",
            "Release de teste somente Windows x64 Portable, sem instalador e sem documentação.",
        ],
    },
    "1.6.15": {
        "title": "Correção do fan-out do Mapa e medidores de recursos",
        "items": [
            "Remove o refresh completo do mapa disparado por cada estação sem marcador.",
            "Impede execuções simultâneas de loadMapData com trava single-flight.",
            "Limita animações ao vivo e deduplica indicadores visuais por estação em cada ciclo.",
            "Adiciona indicadores de CPU e RAM em tempo real na barra superior.",
            "CPU/RAM somam o processo principal e processos filhos do WebView2.",
            "Release de teste somente Windows x64 Portable, sem instalador e sem documentação.",
        ],
    },
    "1.6.14": {
        "title": "RX em transação única",
        "items": [
            "Consolida o processamento de cada pacote APRS recebido em uma única transação SQLite.",
            "Log RX, histórico de pacotes, topologia e estação/track deixam de abrir conexões e commits independentes por pacote.",
            "Mantém o housekeeping em lotes introduzido na v1.6.13.",
            "Registra transações RX lentas no diagnóstico para identificar gargalos residuais.",
            "Objetivo principal: reduzir CPU, contenção do banco e starvation das rotas HTTP.",
            "Release de teste somente Windows x64 Portable, sem instalador e sem documentação.",
        ],
    },
    "1.6.13": {
        "title": "Redução de CPU e housekeeping SQLite",
        "items": [
            "Remove as limpezas de tabelas grandes executadas a cada pacote APRS recebido.",
            "Housekeeping de packets, aprs_log e topology_events passa a ocorrer em lotes a cada 1.000 registros ou 5 minutos.",
            "A remoção do histórico excedente passa a usar corte por chave primária, evitando varreduras completas repetidas.",
            "Reduz a frequência de pollings pesados e atualiza mapa, mensagens, estações e log principalmente quando a aba correspondente está ativa.",
            "Mantém a instrumentação diagnóstica da v1.6.12 para acompanhar eventuais travamentos residuais.",
            "Release de teste somente Windows x64 Portable, sem instalador e sem documentação.",
        ],
    },
    "1.6.12": {
        "title": "Portable de diagnóstico do travamento",
        "items": [
            "Instrumenta cada request do backend local com endpoint, thread, duração e quantidade de requests ativos.",
            "Watchdog interno testa o servidor local e gera dump de todas as threads após falhas consecutivas ou saturação.",
            "Operações SQLite acima de 750 ms e erros de banco passam a ser registrados no diagnóstico.",
            "O log persistente fica na pasta de dados como diagnostics.log e pode ser baixado por /api/diagnostics/log.",
            "A mensagem de timeout informa qual endpoint deixou de responder.",
            "Release de diagnóstico somente Windows x64 Portable, sem instalador e sem documentação.",
        ],
    },
    "1.6.11": {
        "title": "Teste de estabilidade do Portable",
        "items": [
            "Remove PRAGMA journal_mode=WAL do caminho de cada request e deixa a configuração WAL somente na inicialização.",
            "Mensagens multipartes passam a ser registradas em uma única transação SQLite.",
            "Pollings da interface deixam de se sobrepor quando uma chamada demora.",
            "Chamadas ao backend local ganham timeout de 10 segundos em vez de permanecer indefinidamente presas.",
            "Após enfileirar uma mensagem, o botão Enviar é liberado sem aguardar a recarga da lista.",
            "Release de teste somente Windows x64 Portable, sem instalador e sem documentação.",
        ],
    },
    "1.6.10": {
        "title": "Release completa multiplataforma",
        "items": [
            "Consolida a correção do envio de mensagens com fila assíncrona e deduplicação.",
            "Mantém a rotina segura de encerramento e manutenção leve do SQLite.",
            "Corrige definitivamente o pipeline do ícone Windows usando a identidade visual estável.",
            "Aplica todos os patches acumulados também aos builds macOS e à geração do manual.",
            "Publica Windows Setup e Portable, Linux TAR.GZ/AppImage/DEB, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.6.9": {
        "title": "Estabilidade de mensagens e build",
        "items": [
            "Mantidas as correções de fila assíncrona e deduplicação no envio de mensagens.",
            "Mantida a rotina de encerramento e manutenção leve do SQLite.",
            "Corrigido o teste legado de identidade visual que impedia os builds Windows e Linux.",
            "O build usa temporariamente a logo estável anterior até a logo oficial ser reintegrada com arquivo validado.",
            "Release para Windows x64 e Linux x86_64, sem macOS e sem PDF.",
        ],
    },
    "1.6.8": {
        "title": "Fila de transmissão e estabilidade",
        "items": [
            "Envio de mensagens passa a usar fila assíncrona no backend, evitando travamento da interface.",
            "Cliques repetidos na mesma mensagem em poucos segundos são deduplicados.",
            "O botão Enviar fica bloqueado enquanto a solicitação é registrada.",
            "Falhas de socket deixam de prender a requisição web e passam a acionar recuperação da conexão.",
            "Ao encerrar, a aplicação cancela filas pendentes e executa manutenção leve do SQLite.",
            "Release para Windows x64 e Linux x86_64, sem macOS e sem PDF.",
        ],
    },
    "1.6.7": {
        "title": "Primeira release Linux atualizada",
        "items": [
            "Build Linux x86_64 com pacote TAR.GZ, AppImage e DEB.",
            "Aplicadas no Linux as correções acumuladas das versões 1.6.4 a 1.6.6.",
            "A logo APRS oficial é usada na interface e no ícone dos pacotes Linux.",
            "Incluídos testes smoke em Ubuntu 22.04 e 24.04.",
            "Release somente Linux, sem Windows, macOS ou PDF.",
        ],
    },
    "1.6.6": {
        "title": "Configuração, manutenção e identidade visual",
        "items": [
            "Corrigido o salvamento da aba Configuração e o fluxo Salvar e sair.",
            "Seletor de idioma passa a exibir bandeiras reais do Brasil e dos EUA no Windows.",
            "Adicionado Limpar tudo com destaque e confirmação dupla, preservando configuração e favoritos.",
            "A logo APRS fornecida passa a ser usada na aplicação e como base do ícone Windows.",
            "Release somente Windows x64, sem PDF.",
        ],
    },
    "1.6.5": {
        "title": "Manutenção e notificações",
        "items": [
            "Novo bloco Manutenção centraliza as ações de limpeza do banco.",
            "Notificações do navegador agora têm volume, seleção de som e botão de teste.",
            "A barra de histórico/replay do Mapa fica oculta por padrão e pode ser aberta pelo cabeçalho.",
            "Corrigido o envio para destinatários com sufixo alfanumérico, incluindo PY2OFU-D.",
            "Release somente Windows x64, sem PDF.",
        ],
    },
    "1.6.4": {
        "title": "Correções de Mensagens e Replay",
        "items": [
            "Corrigido o envio de mensagens pelo botão Enviar e pela tecla Enter.",
            "Corrigido o filtro por origem na aba Mensagens.",
            "Replay volta a mostrar os pacotes trafegando entre os nós, com rastro visual.",
            "Estações móveis continuam deixando tracklog progressivo durante o replay.",
            "Incluído teste de regressão para evitar replay apenas com highlight das estações.",
            "Release somente Windows x64 Portable.",
        ],
    },
    "1.6.3": {
        "title": "Replay móvel e seleção rápida de período",
        "items": [
            "Seleção rápida do replay: 1 h, 12 h, 24 h, 7 dias ou todo o histórico.",
            "Removidos os campos manuais De/Até e compactada a área de período.",
            "Estações móveis agora se deslocam durante o replay e deixam o tracklog progressivamente.",
            "Build desta versão restrito ao Windows x64, sem geração de PDF.",
        ],
    },
    "1.6.2": {
        "title": "Replay da Rede e melhorias de estabilidade",
        "items": [
            "Replay da Rede com linha do tempo, seek e velocidades de 0,25x a 20x.",
            "Controles de animação movidos para a parte inferior do Mapa.",
            "Som e animação de atividade limitados às estações visíveis no enquadramento atual.",
            "Indicador RX/TX de atividade na barra superior.",
            "Legenda do Mapa sincronizada com cores e espessuras configuradas.",
            "Correção da espessura da topologia e salvamento centralizado no rodapé da Configuração.",
            "Auto-update removido: o cliente apenas informa quando há uma nova versão.",
            "Verificação de versão com timeout e recuperação automática após falhas.",
            "Botão Ver logs no popup da estação.",
        ],
    },
}


def notes_for(version: str) -> dict[str, Any]:
    data = VERSION_NOTES.get(str(version or "").strip(), {})
    return {
        "version": str(version or "").strip(),
        "title": str(data.get("title") or ""),
        "items": list(data.get("items") or []),
    }
