from __future__ import annotations

from typing import Any

VERSION_NOTES: dict[str, dict[str, Any]] = {
    "1.14.16": {
        "title": "Tracklog acompanhado e rotas totalmente visíveis",
        "items": [
            "Clique em um tracklog para mantê-lo centralizado conforme novas posições chegam, preservando o zoom atual.",
            "Arrastar o mapa encerra o acompanhamento; mudar apenas o zoom mantém o seguimento ativo.",
            "Rotas abertas pelo Ranking passam a usar o maior zoom possível que ainda mostra todo o trajeto e todas as estações envolvidas.",
            "O enquadramento considera a área ocupada pelo painel de rota para não esconder trechos atrás do popup.",
            "Todos os nós listados na rota recebem identificação visual no mapa, mesmo quando o marcador APRS normal não está disponível.",
        ],
    },
    "1.14.15": {
        "title": "Rotas RF completas em malhas densas",
        "items": [
            "A pesquisa de rotas deixa de encerrar após um pequeno número de caminhos encontrados e passa a usar busca best-first sobre caminhos simples.",
            "O mapa mantém visível todo o corredor de enlaces RF elegíveis entre origem e destino, mesmo quando somente as melhores rotas são listadas no painel.",
            "Evidência RF direta é priorizada sobre RF inferido do path, sem usar distância geográfica como veto.",
            "Cada rota passa a informar quantos trechos são diretos, inferidos ou legados.",
            "O horizonte padrão da pesquisa sobe de 8 para 12 hops; o limite de rotas continua sendo apenas um limite de apresentação.",
            "Se a proteção contra explosão combinatória for atingida, a interface informa explicitamente que a busca foi truncada sem esconder os enlaces elegíveis.",
        ],
    },
    "1.14.14": {
        "title": "Consolidação do modelo RF observado",
        "items": [
            "A interface passa a usar consistentemente o termo RF observado após a restauração do algoritmo permissivo.",
            "O painel de rotas deixa de exibir confiança/heurística obsoleta e mostra a origem real da classificação do enlace.",
            "Autocomplete e mensagens de rota passam a falar em rotas RF observadas, alinhados ao backend.",
            "A pesquisa de duas estações mantém o mesmo foco exclusivo dos Recordes RF, com rotas alternativas e restauração da visualização.",
            "Mantidas as correções de Estatísticas sem rolagem vertical interna e a separação objetiva entre RF e APRS-IS/Internet.",
        ],
    },
    "1.14.13": {
        "title": "Rotas RF observadas e foco unificado no mapa",
        "items": [
            "A pesquisa manual de duas estações passa a usar o mesmo foco exclusivo dos Recordes RF.",
            "Somente origem, destino, intermediários e enlaces pertencentes às rotas encontradas permanecem visíveis durante a análise.",
            "O grafo RF volta a aceitar enlaces observados sem filtros de exclusão por distância, quantidade mínima de observações ou poucos hops.",
            "APRS-IS/Internet continua separado e nunca completa uma rota RF.",
            "O ranking de software e os demais blocos das Estatísticas permanecem no fluxo vertical principal, sem scroll vertical interno.",
        ],
    },
    "1.14.12": {
        "title": "RF confirmado e Estatísticas sem scroll interno",
        "items": [
            "Rotas e Recordes RF passam a exigir trechos RF confirmados por uma heurística de evidência e plausibilidade.",
            "Trechos muito longos com pouca evidência são rebaixados, enquanto propagação excepcional com evidência direta forte continua válida.",
            "O painel de Análise de rota RF passa a ser arrastável dentro do mapa.",
            "O painel exibe confiança e justificativa resumida da classificação RF.",
            "A aba Estatísticas deixa de usar rolagem vertical interna nos cards, inclusive no ranking de software/aplicações.",
        ],
    },
    "1.14.11": {
        "title": "Recordes RF refinados e cabeçalho compacto",
        "items": [
            "Os Recordes RF passam a ser ordenados pela distância direta entre as estações extremas.",
            "A distância total da rota pelos hops permanece disponível apenas como informação complementar.",
            "Cada par de estações aparece uma única vez no ranking, mesmo quando existem caminhos alternativos.",
            "O botão Rotas RF do mapa passa a se chamar Pesquisar.",
            "O cabeçalho usa os rótulos curtos Atualizada, TNC e APRS-IS, com LEDs vermelho/verde para os estados de conexão.",
        ],
    },
    "1.14.10": {
        "title": "Recordes RF e mapa mais responsivo",
        "items": [
            "A barra de controles do mapa passa a quebrar de forma responsiva e recalcula a altura útil do mapa.",
            "Campos de origem/destino e demais controles ficam mais compactos para aproveitar melhor a largura disponível.",
            "Os dois campos de indicativo ganham sugestões progressivas baseadas no grafo RF disponível.",
            "A aba Estatísticas deixa de usar rolagem vertical interna nos principais rankings.",
            "Novo bloco Recordes RF lista as rotas completas mais longas por distância total.",
            "Ao clicar em um recorde, somente aquela rota e as estações envolvidas permanecem visíveis no mapa até limpar o foco.",
        ],
    },
    "1.14.9": {
        "title": "Pesquisa e análise de rotas RF no mapa",
        "items": [
            "O Mapa ganha pesquisa por indicativo e localização rápida da estação.",
            "Após escolher a origem, o segundo indicativo mostra somente destinos com rota RF completa observada no período atual.",
            "A análise enumera múltiplas rotas RF completas, ocultando temporariamente enlaces alheios ao filtro.",
            "O painel lateral detalha hops, distâncias por trecho e total, distância direta, evidência temporal e observações.",
            "APRS-IS/Internet é excluído do grafo usado para completar rotas RF.",
            "O hover e o popup dos enlaces passam a informar também o comprimento em metros ou quilômetros.",
        ],
    },
    "1.14.8": {
        "title": "Retenção granular e resposta automática",
        "items": [
            "Configuração ganha presets independentes de retenção: Não apagar, 1 dia, 1 semana e 1 mês.",
            "Mensagens, tracklogs, enlaces/topologia, logs APRS, TNC e notificações podem ter janelas distintas sem reduzir automaticamente valores existentes.",
            "Limpeza de topologia remove também enlaces agregados sem evidência recente e informa registros removidos e espaço recuperável.",
            "Mensagens diretas podem receber resposta automática com texto customizável e cooldown por remetente.",
            "ACK/REJ, queries, boletins e grupos não acionam autoresposta; proteção por cooldown evita loops entre estações automáticas.",
            "Autoresposta respeita o meio recebido e as mesmas guardas de segurança de TX APRS-IS/RF.",
            "Mensagens automáticas ficam identificadas no histórico persistido.",
        ],
    },
    "1.14.7": {
        "title": "Backend mais responsivo com banco crescente",
        "items": [
            "O schema TNC passa a ser criado/migrado uma vez por banco, evitando DDL repetitivo nos pollings.",
            "Atualizações APRS contínuas deixam de invalidar imediatamente o snapshot completo do mapa.",
            "Rebuilds pesados do mapa são coalescidos em uma janela curta de 30 segundos.",
            "SQLite ganha índices adicionais para packets/topologia e ajustes conservadores de cache, temp_store e WAL.",
            "A validação de posições reutiliza as estações já carregadas no build do mapa.",
            "A retenção padrão não foi reduzida para 5 dias; as preferências do usuário permanecem preservadas.",
        ],
    },
    "1.14.6": {
        "title": "Cliente terrestre mais leve e enlaces iGate restaurados",
        "items": [
            "O módulo SAT/ISS foi removido estruturalmente do aplicativo principal, incluindo backend, interface, assets e serviços exclusivos.",
            "A dependência orbital SGP4 deixa de fazer parte do build e o cliente volta ao foco APRS terrestre.",
            "Enlaces APRS-IS confirmados voltam a aparecer mesmo quando o mesmo par também foi observado por RF.",
            "RF e Internet são mantidos como evidências independentes; um iGate não converte automaticamente um enlace RF em Internet.",
            "Em evidência mista, RF permanece sólido e APRS-IS permanece tracejado com contadores próprios.",
            "O CI e os testes foram limpos das dependências SAT e ganharam regressões específicas para a nova topologia.",
            "APRS via satélite fica reservado para uma futura aplicação dedicada.",
        ],
    },
    "1.14.5": {
        "title": "Configuração robusta em instalação real e correção SAT",
        "items": [
            "Salvar configuração recalcula as diferenças reais e envia somente os campos alterados.",
            "Salvar e sair exibe o erro verdadeiro do backend e só navega depois de persistir.",
            "Descartar alterações restaura o baseline local sem depender de rede/backend.",
            "Continuar na Configuração preserva os valores editados sem chamadas externas.",
            "GET de configuração atrasado não apaga nem rebaselina uma edição feita pelo usuário.",
            "Configurações migradas podem salvar um campo independente mesmo que outro valor legado esteja fora da faixa atual.",
            "Serviços monitorados do SAT deixam de usar $().forEach e passam a querySelectorAll().",
            "Falhas de renderização SAT deixam de ser rotuladas como erro de cálculo orbital.",
            "Novos testes de interface reproduzem botão inferior, backend lento, erro real e descarte offline.",
        ],
    },
    "1.14.4": {
        "title": "Configuração, enlaces Internet e envio rápido por clique direito",
        "items": [
            "Salvar e sair, Descartar e sair e Continuar na Configuração têm navegação consistente e feedback de erro.",
            "Clique direito numa estação abre Mensagem rápida para o indicativo selecionado.",
            "Enlaces iGate/Internet confirmados não somem por filtros independentes de marcadores no Mapa.",
            "A classificação RF/Internet continua respeitando evidência real, incluindo qAR/qAO, qAr e pares mistos.",
            "Ícones do sistema ganham versão simplificada de alto contraste; logo oficial permanece na interface e manual.",
            "Corrigido o salvamento de alertas que falhava com $(...).forEach is not a function.",
            "Mapa ganha janelas de 15 e 30 minutos com suporte fracionário real no backend.",
            "Aba SAT evita compressão ilegível da barra lateral e recalcula o mapa após redimensionamento.",
            "Saúde do SQLite na Configuração é leve e não executa scans profundos automaticamente em bancos grandes.",
            "Adicionadas regressões pytest e testes de interface Chromium/Playwright.",
            "TM-D700 removido administrativamente do backlog sem declarar validação física.",
        ],
    },
    "1.14.3": {
        "title": "Beacon manual no cabeçalho e classificação de digipeater corrigida",
        "items": [
            "A barra principal ganha botão Enviar Beacon para disparo manual rápido usando o mesmo pipeline já existente.",
            "Os botões de beacon do cabeçalho e da Configuração são bloqueados durante o envio para evitar duplicidade por clique repetido.",
            "O classificador de interação deixa de usar o frame bruto/path como prova de infraestrutura.",
            "WIDE1-1/WIDE2-1 no path de uma estação comum não a transforma em digipeater.",
            "O backend expõe evidência de infraestrutura baseada em hop intermediário realmente observado ou iGate de q-construct.",
            "Objetos/itens e infraestrutura comprovada sem evidência bidirecional continuam protegidos.",
            "A validação física do TM-D700 continua pendente de hardware real.",
        ],
    },
    "1.14.2": {
        "title": "Cobertura RF em heatmap e AIS ampliado",
        "items": [
            "Mapa ganha camada Cobertura RF em heatmap Canvas, ponderada por RSSI/SNR quando disponíveis e por densidade RF como fallback.",
            "O heatmap respeita período e zoom e integra Selecionar tudo / Remover tudo do menu Ver.",
            "Popup AIS passa a mostrar mais dados amigáveis: nome, MMSI, IMO, indicativo, tipo, navegação, SOG/COG, proa, destino, ETA, calado e dimensões.",
            "Códigos AIS comuns são traduzidos para descrições legíveis.",
            "Foto real continua dependente do provedor configurável por MMSI/IMO; sem foto, a representação é explicitamente marcada como ilustrativa.",
            "Falhas do enriquecimento AIS não bloqueiam o popup.",
            "O backlog antigo de zoom é encerrado porque o step já é configurável.",
            "A validação física do TM-D700 continua pendente de hardware real.",
        ],
    },
    "1.14.1": {
        "title": "SAT mais rápido, compacto e operacional",
        "items": [
            "Corrigida a regressão em que a ISS selecionada podia não aparecer no mapa até o próximo polling.",
            "A ISS/NORAD 25544 passa a ser o único satélite selecionado por padrão em instalações novas.",
            "Mapa, estações recebidas e mensagens ganham prioridade visual; configurações secundárias ficam recolhidas.",
            "O contador de passagem fica alinhado à esquerda e identifica claramente o satélite, AOS/LOS e passagem ativa.",
            "O menu superior passa a mostrar SAT.",
            "O sino de notificações é removido da barra superior; o Centro de notificações continua disponível em Configuração.",
            "Corrigida a preferência de alerta de nova estação para respeitar imediatamente o estado desmarcado.",
        ],
    },
    "1.14.0": {
        "title": "Operação APRS por satélite em uma única aba",
        "items": [
            "A aba Satélites / ISS ganha estações recebidas, detalhes e envio de mensagens APRS sem sair da tela.",
            "Mensagens reutilizam o mesmo motor da aba Mensagens, com histórico, ACK/REJ, rota e path.",
            "Seleção de satélites fica compacta/recolhível e ganha pesquisa rápida por nome, indicativo ou NORAD.",
            "Contador HH:MM:SS é movido para a barra operacional, fica maior e considera apenas selecionados ou favoritos.",
            "Novo perfil Beacon Satélite / curto com path próprio, comentário enxuto, intervalo, elevação mínima, cobertura e parada no LOS.",
            "Beacon satelital exige consentimento explícito e reutiliza todas as proteções do TNC/RF.",
            "Saúde operacional do TNC fica restrita à aba TNC / RF.",
        ],
    },
    "1.13.0": {
        "title": "Satélites APRS refinados e diagnóstico TNC por protocolo",
        "items": [
            "Catálogo de Satélites / ISS mostra APRS confirmado por padrão e separa Packet/AX.25 genérico.",
            "Contador HH:MM:SS da próxima passagem APRS e despertador configurável de aproximação da cobertura.",
            "TLE multifonte com CelesTrak Amateur/Stations, AMSAT, prioridades, testes, fallback e atualização diária.",
            "Satélites podem ser monitorados, ignorados ou marcados fora do ar, com serviços APRS/SSTV/telemetria/voz/packet independentes.",
            "Seleção de satélites ganha Marcar tudo e Desmarcar tudo.",
            "TM-D700/TM-D710 ganham perfil próprio, separando serial 9600 de packet RF 1200/9600 e distinguindo terminal de KISS.",
            "Diagnóstico serial mostra amostra limitada ASCII/HEX e evita sugerir menu KISS inexistente para TM-D700 em PKT.",
            "Autoteste TNC passa a declarar quais camadas foram testadas e mantém TX físico RF como não validado.",
        ],
    },
    "1.12.0": {
        "title": "Satélites / ISS, topologia RF e janelas destacáveis",
        "items": [
            "Nova aba Satélites / ISS com mapa orbital dedicado, posição, rotas e footprint.",
            "Agenda SGP4 de passagens com AOS, TCA, LOS, elevação máxima e azimutes.",
            "Catálogo packet/APRS via SatNOGS e TLE via CelesTrak, com cache, fonte e época.",
            "Alertas configuráveis de passagem com frequências, modo e integração ao Centro de notificações.",
            "Mapa principal ganha opção Ver → Satélites / ISS.",
            "Topologia preserva o meio real RF recebido pelo TNC e remove a antiga reconversão automática para Internet.",
            "Mensagens, Estações e Logs usam controles minimizar, maximizar/restaurar e fechar/encaixar no padrão Windows.",
            "Aba Logs passa a ser destacável e a geometria das janelas pode ser restaurada.",
            "Campo de busca da extremidade esquerda da barra do mapa foi removido.",
        ],
    },
    "1.11.1": {
        "title": "Topologia RF até iGate corrigida",
        "items": [
            "Enlaces que possuem evidência RF permanecem RF mesmo quando o destino é um iGate.",
            "Linha tracejada fica reservada a enlaces 100% Internet/APRS-IS.",
            "Quando o mesmo par foi observado por RF e Internet, o mapa mostra RF e preserva as contagens separadas dos dois meios.",
            "Popup e hover exibem o meio efetivamente observado sem inferir Internet apenas pelo papel de iGate.",
            "Adiciona regressões para qAR/qAO, evidência mista e Internet-only.",
        ],
    },
    "1.11.0": {
        "title": "Confiabilidade operacional, TNC e observabilidade",
        "items": [
            "Contadores RX/TX do TNC são reconciliados com os frames persistidos da sessão, evitando indicadores presos em zero.",
            "Novo health check classifica automaticamente transporte, KISS, AX.25, RX e RX/TX.",
            "Autoteste interno KISS/AX.25 valida RX, TX, ACK e parser sem rádio físico.",
            "Timeline de saúde do TNC e botão Copiar diagnóstico facilitam suporte.",
            "Centro de notificações mantém histórico persistente dos alertas.",
            "Saúde/retenção SQLite mostra integridade, tamanho, WAL, fragmentação e permite política por tipo de dado.",
            "Perfil operacional da estação mostra tráfego, mensagens, paths e Ouvido por.",
            "Inclui as correções completas de alertas da v1.10.1.",
            "Release completa multiplataforma com Manual PDF.",
        ],
    },
    "1.10.1": {
        "title": "Correções completas dos alertas configuráveis",
        "items": [
            "Estação apareceu e Estação desapareceu passam a usar transições reais de presença, evitando alertas repetidos por simples atualização de last_heard.",
            "Favorito apareceu respeita sua preferência independente e a mesma lógica de reentrada real.",
            "Nova mensagem ganha deduplicação por ID.",
            "TNC e APRS-IS só alertam quando a conexão cai inesperadamente, não em desconexão voluntária.",
            "Problema no banco gera um aviso por episódio e rearma após normalização.",
            "Alterações nos checkboxes de alerta são aplicadas e persistidas imediatamente.",
            "Adiciona regressões para preferências desmarcadas, presença, deduplicação e transições de conectividade.",
        ],
    },
    "1.10.0": {
        "title": "QRZ, AIS, métricas RF e qualidade contínua",
        "items": [
            "Perfis de estação podem ser enriquecidos pelo QRZ.com usando a API XML oficial, com foto, nome, cidade, região, país, grid e cache.",
            "Fotos AIS passam por provedor externo configurável e associação por MMSI/IMO, sem scraping textual ambíguo.",
            "A camada RF aceita RSSI, SNR, DCD, frequência, canal e fonte somente quando o equipamento/provedor realmente fornecer.",
            "O TM-D700 ganha diagnóstico específico e roteiro de validação física; o Client não declara teste físico que não foi executado.",
            "O Windows Portable ganha soak test com perfis de 24 h, 72 h e 7 dias e relatório de crescimento de memória.",
            "A CI executa matriz de migração histórica e auditoria contínua de traduções PT-BR/EN/ES/FR.",
            "Release completa multiplataforma com Manual PDF.",
        ],
    },
    "1.9.0": {
        "title": "Painéis destacáveis, busca global, backup, alertas e operação avançada",
        "items": [
            "Mensagens e Estações podem ser destacadas sobre o mapa, arrastadas, redimensionadas, minimizadas e encaixadas novamente.",
            "Busca Global localiza estações, objetos, WX, AIS e infraestrutura a partir de indicativo, nome, comentário ou status.",
            "Estações ganham organização por nome amigável, cor, nota e grupos definidos pelo usuário.",
            "Backup completo inclui banco, mensagens, estações, favoritos, tracklogs, agendamentos, grupos e preferências, com restauração validada.",
            "Alertas configuráveis cobrem aparecimento/desaparecimento de estações, favoritos, mensagens, TNC, APRS-IS e integridade SQLite.",
            "Timeline unificada reúne mensagens, posições, queries e tráfego RF.",
            "Modo apresentação coloca o mapa em tela cheia para clubes, encontros e acompanhamento operacional.",
            "TNC/RF ganha Testar TNC não destrutivo, preservando KISS Serial/TCP e AGWPE.",
            "Mantém saúde da rede, comparação entre períodos, grafo de comunicação, CSV, GeoJSON, pacote de suporte e Linux ARM64.",
            "A validação física do Kenwood TM-D700 em PKT permanece dependente do equipamento real.",
            "Release completa para Windows x64/ARM64, Linux x86_64/ARM64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.18": {
        "title": "AGWPE, análise avançada, exportações e Linux ARM64",
        "items": [
            "Adiciona AGWPE TCP como terceiro transporte TNC, preservando KISS TCP e KISS Serial.",
            "Adiciona busca rápida por indicativo no Mapa e painel lateral responsivo de estação.",
            "Estatísticas ganham saúde da rede, comparação com período anterior e grafo visual interativo de comunicação.",
            "Adiciona exportações CSV e GeoJSON por período e pacote ZIP de diagnóstico sanitizado.",
            "Inclui simulador KISS para fragmentação, duplicidade e cenários multi-hop sem rádio físico.",
            "Pipeline de produção passa a gerar Linux ARM64 e o updater seleciona assets conforme a arquitetura.",
            "Mantém a validação física específica do Kenwood TM-D700 em modo PKT como pendência de hardware real.",
            "Métricas RSSI/SNR/DCD continuam condicionadas ao que o modem/TNC realmente fornecer; nenhum valor é inventado.",
            "Release completa para Windows x64/ARM64, Linux x86_64/ARM64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.17": {
        "title": "Mensagens agendadas, zoom configurável e TNC mais claro",
        "items": [
            "Adiciona mensagens programadas com envio único ou recorrência semanal.",
            "Agendamentos podem usar estação específica, lista de estações, boletim APRS ou grupo APRS.",
            "Listas reutilizáveis de destinatários permitem enviar individualmente para vários indicativos com intervalo configurável.",
            "Permite editar, ativar/desativar, excluir e Executar agora, além de mostrar próxima/última execução e resultado.",
            "Falhas podem pular a ocorrência ou ser tentadas novamente após período configurável.",
            "Agendamentos e listas ficam persistidos no SQLite com proteção contra execução duplicada da mesma ocorrência.",
            "Configuração ganha step do zoom em 0,05 / 0,10 / 0,25 / 0,50 / 1,00, aplicado imediatamente ao Leaflet.",
            "TNC/RF deixa de tratar serial aberta sem KISS válido como estado de sucesso e passa a sinalizar atenção.",
            "Mantém aberta a validação física específica do Kenwood TM-D700 em modo PKT.",
            "Release completa para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.16": {
        "title": "Filtros compartilhados, Conteúdo e zoom mais fino",
        "items": [
            "Corrige o indicativo de Adriano para PP5AU.",
            "O mapa passa a usar zoom em passos de 0,10 e roda do mouse mais gradual.",
            "Mensagens ganha menu Conteúdo com Mensagens, Boletins, Grupos e Telemetria, além de Marcar tudo e Desmarcar tudo.",
            "Estações e Mensagens passam a ter o mesmo menu Ver de tipos de estação usado pelo Mapa.",
            "Mapa, Estações e Mensagens compartilham o mesmo estado central de filtros.",
            "Mensagens não classificáveis permanecem visíveis por segurança.",
            "Um catálogo completo de estações evita interferência do filtro textual da aba Estações na classificação das Mensagens.",
            "Os botões Ver e Conteúdo sinalizam visualmente quando há filtros ativos.",
            "Mantém o diagnóstico TNC/RF da v1.8.15 e a pendência de validação física do TM-D700 em PKT.",
            "Release completa para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.15": {
        "title": "Mensagens, zoom, estações e diagnóstico TNC/RF",
        "items": [
            "Corrige o indicativo de Adriano para PP5AU na aba Sobre.",
            "Adiciona filtros persistentes para mostrar/ocultar mensagens e boletins, mantendo o filtro de telemetria.",
            "O mapa passa a aceitar zoom fracionário em passos de 0,25 e persiste o nível intermediário.",
            "A lista de Estações ganha ordenação por ícone/tipo, ordem visual estável e novas estações adicionadas ao final da visualização corrente.",
            "Adiciona mensagem rápida diretamente na lista de Estações, preservando texto, filtros e rolagem entre destinatários.",
            "Adiciona proteção opcional para DMR, D-Star e SSIDs -12 a -15 e sincroniza a lista com os filtros do menu Ver.",
            "TNC/RF diferencia serial conectada, bytes recebidos, KISS reconhecido, AX.25 válido e TX entregue ao transporte.",
            "O diagnóstico do Kenwood TM-D700 documenta o modo PKT e evita tratar porta aberta como RX/TX RF confirmado.",
            "Release completa para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.14": {
        "title": "Backlogs consolidados: APRS explicado e relevo DEM sombreado",
        "items": [
            "Fecha integralmente os cinco backlogs consolidados: rota por mensagem, responsividade, bloqueio de interações sem suporte bidirecional, elevação/DEM e aba Sobre.",
            "A aba Sobre passa a explicar explicitamente o que é APRS, incluindo posição, mensagens, telemetria, meteorologia, RF e APRS-IS.",
            "A explicação de APRS acompanha o idioma selecionado em Português, English, Español e Français.",
            "Relevo com corte passa a aplicar hillshade calculado diretamente sobre as altitudes do DEM Terrarium, preservando o corte por cota e a opacidade configurável.",
            "Mantém slider vertical, máximo padrão de 3.000 m, limite configurável de 100 a 9.000 m e persistência da última cota, máximo e opacidade.",
            "Mantém Automático / APRS-IS / RF direto / RF personalizado por mensagem e as regras de baixa altura para 1360×768 e 1280×720.",
            "Mantém desabilitadas Mensagem, queries, Ping/ACK e Trace para alvos identificados como não interativos sem evidência de capacidade bidirecional.",
            "Preserva o hotfix de migração SQLite da v1.8.12 e todas as funcionalidades da série 1.8.",
            "Release completa para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.13": {
        "title": "Consolidação dos backlogs de mensagens, responsividade, interação e mapa",
        "items": [
            "Consolida e protege por regressão a seleção de rota por mensagem: Automático, APRS-IS, RF direto e RF personalizado.",
            "Valida a interface de baixa altura usada em 1360×768 e 1280×720, mantendo Mensagens e ações do popup acessíveis sem alterar a geometria global do mapa.",
            "Mantém bloqueadas as interações APRS para objetos/itens e infraestrutura sem evidência de capacidade bidirecional, incluindo mensagens, queries, Ping/ACK e Trace.",
            "Consolida Relevo com corte baseado em DEM real, slider vertical, máximo padrão de 3.000 m configurável de 100 a 9.000 m e opacidade persistente.",
            "Consolida a aba Sobre com apresentação do projeto, contatos, tiny.cc/aprs, divulgação APRS e traduções PT-BR, EN, ES e FR.",
            "Preserva o hotfix de migração SQLite da v1.8.12 e adiciona testes para impedir regressão dos cinco requisitos consolidados.",
            "Release completa para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.12": {
        "title": "Hotfix de migração para bancos existentes",
        "items": [
            "Corrige o erro no such column: medium ao iniciar com banco criado por versões anteriores.",
            "As colunas medium e rx_fingerprint agora são migradas antes da criação dos índices dependentes.",
            "A atualização preserva o banco existente; não é necessário apagar histórico, mensagens, estações, logs ou tracklogs.",
            "Inclui regressão que recria um schema legado de packets e valida a migração completa.",
            "Mantém RF × APRS-IS nas Estatísticas, estações RF em TNC/RF e a organização visual da Configuração da v1.8.11.",
            "Release completa para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.11": {
        "title": "Recepção RF nas Estatísticas e organização visual da Configuração",
        "items": [
            "Pacotes passam a preservar explicitamente o meio de entrada RF ou APRS-IS.",
            "A lista de estações ouvidas por RF usa evidência persistente e mostra recepções, pacotes RF, distância, path e recepção direta/via digi quando conhecida.",
            "Estatísticas ganha resumo RF × APRS-IS e colunas RF/APRS-IS no ranking de estações.",
            "A mesma transmissão observada pelos dois meios é correlacionada em um total lógico deduplicado sem apagar a evidência de cada meio.",
            "Novos diagnósticos registram novas estações RF e resumos periódicos do RX TNC/KISS.",
            "Os títulos dos blocos da aba Configuração passam a usar laranja e fonte maior para reforçar a hierarquia visual.",
            "Inclui regressões para RF-only, RF+APRS-IS, deduplicação entre meios e estilo da Configuração.",
            "Release completa para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.10": {
        "title": "Controle único de conexão e agradecimentos aos colaboradores",
        "items": [
            "O cabeçalho passa a usar um único componente para estado e ação da conexão APRS-IS.",
            "O controle mostra Desconectado, Conectando, Reconectando, Conectado e verificado, Conectado sem verificação e Conexão perdida.",
            "A ação Conectar/Desconectar usa wanted/connected/verified do backend e não depende mais do texto do botão.",
            "Cliques concorrentes são bloqueados durante a execução da ação, preservando validação de configuração e reconexão.",
            "A aba Sobre ganha uma seção de Agradecimentos / Colaboradores.",
            "São reconhecidos PP5AU Adriano, PY4EI Allan, PU2MUS Marco, PP5PK Daniel Kondlatsch, PT2YW Ywstter e PT2PAG Paulo Galvão.",
            "Textos atualizados em PT-BR, EN, ES e FR.",
            "Release completa para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.9": {
        "title": "Atualizações configuráveis e popups amigáveis de objetos APRS",
        "items": [
            "Checagem automática de novas versões passa a 15 minutos por padrão, com intervalo configurável entre 5 e 1.440 minutos.",
            "O novo intervalo é persistido e aplicado sem reiniciar o Client.",
            "Objetos APRS passam a preservar mais telemetria estruturada, incluindo velocidade, curso, path, meteorologia, primeira recepção e altitude máxima.",
            "Balões/radiossondas recebem popup amigável com dados de voo e meteorologia quando disponíveis.",
            "WX, AIS, repetidores, DMR, D-Star, alertas, itens APRS e outros objetos usam apresentação contextual.",
            "Dados técnicos ficam recolhidos e preservam formato APRS, path e pacote bruto.",
            "Campos ausentes são omitidos e objetos não identificados usam apresentação genérica sem inferências forçadas.",
            "Traduções PT-BR, EN, ES e FR atualizadas.",
            "Release completa para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.8": {
        "title": "Desempenho do mapa, SQLite e polling serial",
        "items": [
            "Mapa /api/map-data passa a usar single-flight global e cache de snapshot para impedir consultas pesadas concorrentes.",
            "Chamadas simultâneas usam o último mapa válido em vez de ocupar vários workers do servidor.",
            "Remove consultas EXISTS correlacionadas por estação em Mapa e Estações.",
            "Adiciona índices SQLite para mensagens, ACK/REJ e queries APRS usadas na evidência de interação.",
            "O diagnóstico passa a registrar duração e tamanho de cada geração do mapa.",
            "Refresh completo do mapa passa a 15 segundos, preservando o polling independente do tráfego animado.",
            "CIM/PowerShell deixa de participar do polling serial periódico; varredura completa permanece disponível ao reescanear.",
            "Polling serial automático passa a 30 segundos com fontes leves e cache de 60 segundos para scans completos.",
            "Inclui testes de concorrência, cache stale-while-busy e regressões de desempenho.",
            "Release completa para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.7": {
        "title": "Descoberta avançada de equipamentos seriais no TNC / RF",
        "items": [
            "A descoberta serial combina pyserial, Windows CIM/PnP e SERIALCOMM para encontrar mais portas COM.",
            "Nova seção Equipamentos seriais detectados mostra porta, equipamento, chipset/interface, fabricante, VID/PID, serial/HWID e estado.",
            "Suporte explícito de identificação de interfaces CH9102/CH340/CH341, CP210x, FTDI e CDC/ACM.",
            "A porta COM pode ser escolhida pela lista de equipamentos ou digitada manualmente.",
            "Novo botão Reescanear e atualização periódica enquanto a aba TNC / RF está aberta.",
            "Radtel RT-950 Pro só recebe identificação nominal quando os metadados do sistema indicam o modelo.",
            "CH9102 recebe orientação condicional para Radtel RT-950 Pro em TNC UART; quando identificado, usa 115200 bps.",
            "Mensagens de erro de abertura serial foram detalhadas e a enumeração completa é registrada no diagnóstico.",
            "Inclui testes com múltiplas portas simultâneas, incluindo COM6/CH9102 e COM10/CH340.",
            "Release completa para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.6": {
        "title": "Correção dos itens do mapa e estabilidade do viewport",
        "items": [
            "Corrige a regressão da v1.8.5 em que itens/camadas do mapa podiam deixar de aparecer.",
            "Restaura a geometria global de header/abas/main usada pelo mapa, evitando redimensionamento global em telas de baixa altura.",
            "Mantém as otimizações para 1360×768 restritas à aba Mensagens e ao popup de estação.",
            "O menu Mapa → Ver é renderizado imediatamente, antes mesmo da primeira carga de dados do backend.",
            "O Leaflet recalcula o viewport após resize/orientationchange e recarrega os dados visíveis.",
            "Inclui recuperação única para estado de visibilidade totalmente desabilitado por regressão, preservando Remover tudo quando acionado explicitamente pelo usuário.",
            "O menu Ver permanece disponível mesmo se uma carga de /api/map-data falhar temporariamente.",
            "Preserva integralmente a seleção de rota/path por mensagem introduzida na v1.8.5.",
            "Adiciona testes específicos para categorias do mapa, persistência, recuperação e estabilidade do viewport.",
            "Release completa para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.5": {
        "title": "Rota/path por mensagem e interface otimizada para 1360×768",
        "items": [
            "Adiciona Rota de envio no compositor de mensagens: Automático, APRS-IS, RF direto e RF personalizado.",
            "RF personalizado aceita path por mensagem, como WIDE1-1 ou WIDE1-1,WIDE2-1, com validação AX.25 antes do envio.",
            "O modo Automático preserva APRS-IS como primeira escolha e usa RF direto somente quando necessário e disponível.",
            "Mensagens e retries registram o meio efetivo (APRS-IS/RF) e o path usado no histórico local.",
            "Retry preserva a rota original por padrão; uma seleção explícita no compositor pode substituir a rota/path.",
            "Mensagens RF usam o TNC/KISS existente, respeitando conexão, pausa de TX e confirmação de transmissão.",
            "A interface ganhou regras responsivas por altura para 1360×768 e outras telas baixas.",
            "Popup de estação passa a limitar melhor sua altura e mantém as ações acessíveis com rolagem e barra de ações sticky.",
            "A aba Mensagens reduz cabeçalho/compositor em baixa altura para manter lista, destinatário e envio visíveis.",
            "Inclui traduções PT-BR, EN, ES e FR e testes de regressão para paths, rotas e layout de baixa altura.",
            "Release completa para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.4": {
        "title": "Alertas de recursos e barra do Mapa alinhada à esquerda",
        "items": [
            "Monitora separadamente CPU e memória do PT2VHF APRS Client e do sistema operacional.",
            "Exibe popup não bloqueante somente após condição crítica sustentada, com padrão de 90% e persistência de 30 segundos.",
            "Aplica histerese de recuperação e cooldown padrão de 10 minutos para evitar alertas repetitivos ou oscilantes.",
            "Registra cada alerta crítico no log de diagnóstico com métricas do aplicativo e do sistema.",
            "Permite configurar ativação, limites de CPU/memória, persistência e cooldown em Configuração → Saúde do aplicativo.",
            "A barra da aba Mapa com Histórico, período, Ver, velocidade, tipo de mapa, Camadas e KML passa a ficar alinhada à esquerda.",
            "Inclui traduções PT-BR, EN, ES e FR e testes de regressão para pico curto, condição sustentada, cooldown, recuperação e novo episódio.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.3": {
        "title": "Ranking separado de aplicativos/dispositivos e controles rápidos do Mapa",
        "items": [
            "Estatísticas → Software / dispositivos APRS passa a separar Aplicativos APRS, Dispositivos/Hardware e itens Indeterminados.",
            "Adiciona filtros persistentes para mostrar/ocultar Aplicativos APRS, Dispositivos e Não identificados.",
            "O ranking e os percentuais são recalculados apenas sobre as categorias visíveis, permitindo comparar somente clientes APRS.",
            "PT2VHF APRS Client, APRSdroid, Dire Wolf, UI-View e WinAPRS ficam no grupo de aplicativos quando identificados; rádios D-STAR, rigs, HTs e trackers ficam no grupo de dispositivos.",
            "Identificações ambíguas permanecem Indeterminadas em vez de contaminar o ranking de software.",
            "Mapa → Ver substitui o botão genérico Tudo por Selecionar tudo e Remover tudo.",
            "As ações em Mapa → Ver atualizam imediatamente pais, filhos, filtros dinâmicos e preferências persistidas.",
            "Novos controles e categorias possuem tradução em PT-BR, EN, ES e FR.",
            "Adiciona regressões para classificação APRS, filtros, percentuais visíveis e ações globais do Mapa.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.2": {
        "title": "Porta local automática, filtro AIS e ajustes de interface",
        "items": [
            "O servidor interno passa a reservar automaticamente a primeira porta livre a partir de 8080, avançando para 8081, 8082 e seguintes quando necessário.",
            "A seleção é feita por bind real do servidor, evitando conflito e a condição de corrida de testar/liberar uma porta antes da abertura.",
            "Windows, Linux, macOS, modo navegador e captura do Manual usam a porta efetivamente alocada.",
            "A interface mostra a porta local escolhida e o Windows registra a informação no diagnóstico; uma segunda abertura pode recuperar a URL da instância existente.",
            "Mapa → Ver → Objetos ganha classificação específica AIS, separada de Balão/Radiosonda e dos demais objetos APRS.",
            "A classificação AIS é conservadora e exige identificação por AIS/MMSI ou marcadores equivalentes; símbolo de embarcação isolado não basta.",
            "Os itens de Mapa → Ver permanecem habilitados por padrão em novas configurações, preservando preferências já salvas pelo usuário.",
            "A bandeira grande foi removida da aba Configuração; o seletor de idioma permanece compacto e as bandeiras pequenas do seletor rápido no cabeçalho continuam disponíveis.",
            "Adiciona indicação discreta da Interface local na Configuração e mantém a tradução PT-BR/EN/ES/FR.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.1": {
        "title": "Mapas sem chave, remoção do hillshade e tradução completa do TNC/RF",
        "items": [
            "Remove Relevo sombreado da interface e do carregamento; Relevo com corte permanece como camada de elevação baseada em DEM.",
            "Corrige Claro e Escuro para funcionarem sobre tiles OpenStreetMap sem API key, com estilos visuais locais.",
            "Adiciona CyclOSM, Humanitário / HOT, OSM.DE e ÖPNVKarte como novos mapas-base sem chave.",
            "Mantém OSM, OpenTopoMap e Satélite, com atribuição específica por provedor.",
            "Adiciona fallback automático para OpenStreetMap após falhas repetidas de tiles de um mapa-base alternativo e registra o evento no diagnóstico.",
            "A aba TNC / RF passa a acompanhar PT-BR, EN, ES e FR, incluindo textos estáticos, estados, tabelas, confirmações e mensagens técnicas conhecidas.",
            "A troca de idioma atualiza imediatamente os componentes TNC/RF já abertos, sem reiniciar o cliente.",
            "Atualiza a tradução dos novos mapas-base e da ajuda/configuração de mapas.",
            "Mantém todos os recursos da v1.8.0, incluindo KISS Serial/TCP, Digipeater, iGate inteligente, análise de quem fala com quem e segurança de TX.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.8.0": {
        "title": "TNC KISS, Digipeater, iGate e otimização inteligente de RF",
        "items": [
            "Inicia a série 1.8 com uma nova aba TNC / RF para operação local de rádio além do APRS-IS.",
            "Adiciona KISS TCP e KISS Serial, listagem de portas, reconexão, monitor de frames AX.25/APRS e contadores RX/TX.",
            "Implementa decodificação e geração AX.25 UI, KISS escaping, representação TNC2 e suporte a paths com SSID e indicador de repetição.",
            "Adiciona Digipeater com perfis Fill-in WIDE1-1, Wide/Regional WIDEn-N e aliases personalizados, com supressão de duplicatas, prevenção de loops, limite de hops e rate limit por origem.",
            "Adiciona fila de TX com prioridade para ACK/REJ e mensagens, mantendo telemetria e tráfego de baixa prioridade atrás do tráfego útil.",
            "Adiciona iGate RF→APRS-IS com qAR e iGate APRS-IS→RF restritivo a mensagens destinadas a estações ouvidas diretamente por RF dentro da janela configurada.",
            "Constrói grafo de quem fala com quem usando mensagens e ACK/REJ observados em RF e APRS-IS, com recomendações e modo automático conservador.",
            "Registra frames, estações ouvidas, decisões de digi/iGate e relações de comunicação no SQLite local com retenção configurável.",
            "TX automático, Digipeater e iGate Internet→RF permanecem desligados por padrão e exigem confirmação explícita; há botão PARAR TX para bloqueio imediato sem derrubar RX.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.7.23": {
        "title": "Produção: relevo com corte, hillshade e novos mapas-base",
        "items": [
            "Adiciona Mapa → Camadas → Relevo com corte, usando DEM Terrarium real para mostrar somente terreno igual ou acima da cota selecionada.",
            "O corte é ajustado em tempo real por slider vertical no lado direito do mapa, com cota atual visível e limite máximo padrão de 3.000 m configurável até 9.000 m.",
            "Adiciona controle independente de opacidade do Relevo com corte e persiste cota, máximo do slider e transparência no banco local.",
            "Adiciona Relevo sombreado como camada independente usando Esri World Hillshade, sem acionar o slider de corte.",
            "Adiciona os mapas-base Claro (CARTO Positron) e Escuro (CARTO Dark Matter), mantendo OSM, Topográfico e Satélite.",
            "Mantém Clima/RainViewer independente dos mapas-base e não inclui camada de raios.",
            "Estações APRS, objetos, tracklogs, enlaces, replay e animações permanecem acima das camadas de relevo.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.7.22": {
        "title": "Produção: camada de clima, radar e popup protegido",
        "items": [
            "Adiciona Mapa → Camadas → Clima, com radar de precipitação mais recente disponível no RainViewer sobre qualquer mapa-base.",
            "A camada de clima fica desligada por padrão e pode ser ligada ou desligada independentemente de OSM, Topográfico ou Satélite.",
            "Configuração ganha controle de opacidade do radar, aplicado imediatamente e persistido no banco com migração automática.",
            "O radar é atualizado periodicamente enquanto a camada está ativa e mantém a última imagem válida se uma atualização temporariamente falhar.",
            "O popup de estação passa a usar altura máxima, rolagem interna, keepInView e margem superior de auto-pan para reduzir cortes sob a barra do mapa.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.7.21": {
        "title": "Hover detalhado de enlaces e tracklogs; atualização sem acúmulo",
        "items": [
            "No Mapa, passar o mouse sobre um enlace mostra um painel fixo com origem, destino, tipo RF ou Internet/APRS-IS, sentido, pacotes, primeira/última observação e iGate quando disponível.",
            "Passar o mouse sobre um tracklog mostra início, fim, duração, distância, velocidade média e máxima, posições, coordenadas inicial/final, digipeaters, iGates, caminhos APRS, RSSI/SNR quando disponíveis e período do mapa.",
            "Novos pontos de tracklog passam a persistir path, pacote bruto, RSSI e SNR quando recebidos; históricos antigos continuam compatíveis e exibem apenas os dados que já existiam.",
            "O updater reutiliza sempre o nome oficial do pacote e sobrescreve downloads anteriores, sem gerar cópias numeradas.",
            "Após uma versão iniciar com sucesso, pacotes antigos e downloads parciais são removidos da pasta temporária, preservando somente uma atualização realmente mais nova ainda pendente.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.7.20": {
        "title": "Produção: período das Estatísticas, RF × Internet e primeira configuração",
        "items": [
            "Corrige o filtro por período da aba Estatísticas, que passa a usar sua própria seleção e não mais o período do Mapa.",
            "Mapa e Estatísticas mantêm períodos independentes e persistidos separadamente.",
            "A classificação de topologia preserva qAR/qAO como evidência de recepção direta por RF, inclusive quando TCPIP/TCPXX aparece em outra parte do path; qAr permanece Internet/APRS-IS.",
            "Na primeira execução ou quando a configuração obrigatória estiver incompleta, o aplicativo abre diretamente em Configuração e posiciona o foco no Indicativo.",
            "A página principal do GitHub remove a tabela de contadores de downloads e oferece links diretos para os produtos da Release latest.",
            "O workflow automático que recriava a tabela de contadores de downloads foi desativado no branch principal.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF, publicada como GitHub Release latest após validação integral.",
        ],
    },
    "1.7.19": {
        "title": "Produção: mapa por famílias, estatísticas consolidadas e RF observado",
        "items": [
            "Objetos APRS passam a ser classificados pela semântica do próprio objeto, sem herdar o software/TOCALL da estação publicadora.",
            "A árvore Ver mantém grupos principais mutuamente exclusivos para estações, digipeaters, iGates e objetos.",
            "Estatísticas consolidam atividade e interações em uma única tabela ordenável de estações comuns.",
            "Digipeaters e iGates são excluídos do ranking de estações também pela classificação APRS Device ID, não apenas pela topologia observada.",
            "O ranking mostra indicativo, pacotes úteis, interações, enviadas, recebidas, contatos, última atividade e tipo/aplicação.",
            "O popup da estação mostra as estações comprovadamente recebidas por RF, com quantidade de pacotes e última observação.",
            "Mantém a árvore Ver por famílias, seleção parcial corrigida, flags de idioma e demais correções das versões de validação 1.7.16-1.7.18.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF, publicada como GitHub Release latest após validação integral.",
        ],
    },
    "1.7.18": {
        "title": "Validação Windows x64: seleção parcial do menu Ver",
        "items": [
            "Corrige o caso em que famílias marcadas em Objetos APRS não apareciam no mapa quando o pai estava em estado intermediário.",
            "O estado do grupo pai passa a ser derivado dos filhos: qualquer filho ativo mantém o grupo habilitado.",
            "Pai parcialmente selecionado representa seleção parcial, não grupo desligado.",
            "A mesma regra vale para Estações, Digipeaters, iGates e Objetos APRS.",
            "Marcar o pai ativa todos os filhos; desmarcar o pai desativa todos; marcar apenas algumas famílias mostra somente essas famílias.",
            "Build de validação somente para Windows x64 Portable, destinado ao teste da seleção parcial do menu Ver.",
        ],
    },
    "1.7.17": {
        "title": "Validação Windows x64: filtros Ver por tipo/família",
        "items": [
            "Remove indicativos e objetos individuais da árvore Ver como níveis de filtragem.",
            "Objetos APRS passam a ser agrupados por família funcional, como RDZSonDe, em vez de por indicativo de origem.",
            "Estações, digipeaters e iGates passam a ser agrupados diretamente por produto/tipo, como Bravo Tracker, DMR, D-Star, HBLink, Dire Wolf e Aprx.",
            "Desmarcar uma família oculta todos os itens daquele tipo no mapa, independentemente do indicativo.",
            "A contagem ao lado da família representa quantos itens daquele tipo estão no período atual do mapa.",
            "Filtros antigos da v1.7.16 são migrados para uma nova chave para evitar ocultações indevidas.",
            "Build de validação somente para Windows x64 Portable, destinado ao teste do agrupamento por famílias.",
        ],
    },
    "1.7.16": {
        "title": "Validação Windows x64: menu Ver hierárquico no Mapa",
        "items": [
            "Substitui Itens do mapa por Ver, com árvore expansível inspirada no filtro de camadas do Google Earth.",
            "Separa Estações, Digipeaters, iGates, Objetos APRS, Tracklogs, enlaces RF, enlaces iGate/APRS-IS e pacotes em movimento.",
            "Estações são subdivididas por classe APRS, fabricante e modelo usando o snapshot offline aprs-deviceid já incluído no aplicativo.",
            "Digipeaters e iGates recebem subdivisões por APRS convencional, LoRa APRS, híbridos Digi+iGate e itens não identificados.",
            "Objetos APRS podem ser expandidos por origem e individualmente ligados/desligados.",
            "Filtros persistem entre execuções e também afetam tracklogs, topologia e animação de pacotes.",
            "Tudo permanece ligado por padrão.",
            "Build de validação somente para Windows x64 Portable, destinado ao teste da nova árvore Ver.",
        ],
    },
    "1.7.15": {
        "title": "Produção: interações APRS inteligentes e Release latest",
        "items": [
            "Digipeaters, hotspots e outras estações de infraestrutura deixam mensagens e queries APRS desabilitadas quando não há evidência de capacidade interativa.",
            "Uma estação de infraestrutura volta a permitir interação automaticamente quando já enviou mensagem, respondeu ACK/REJ, enviou query ou respondeu uma query dirigida.",
            "Objetos e itens APRS permanecem não interativos.",
            "Ações passivas, como Ver logs e histórico de queries, continuam disponíveis.",
            "Mantém a checagem de atualização ao iniciar e a cada 30 minutos.",
            "Status de atualização permanece como Versão atualizada ou Versão X.X.X disponível em laranja e piscando.",
            "Release completa de produção para Windows x64/ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF, publicada como GitHub Release latest.",
        ],
    },
    "1.7.13": {
        "title": "Validação Windows x64: símbolos APRS, animação limpa e status de versão",
        "items": [
            "Objetos APRS passam a usar o símbolo real recebido no pacote; fallback só é usado quando o símbolo não existe.",
            "Remove o rótulo branco APRS-IS da animação, mantendo somente halo e destaque visual.",
            "O destaque de transmissão cresce e volta ao normal em aproximadamente 1 segundo.",
            "Na barra superior, versão atual mostra Versão atualizada.",
            "Quando há atualização, mostra Versão X.X.X disponível em laranja e piscando.",
            "A checagem automática de nova versão permanece a cada 30 minutos.",
            "Build de validação somente para Windows x64 Portable, destinado à validação dos ajustes recentes.",
        ],
    },
    "1.7.12": {
        "title": "Validação Windows x64: todos os marcadores clicáveis no mapa",
        "items": [
            "Cria panes separados no Leaflet para marcadores clicáveis e camadas visuais.",
            "Estações, objetos APRS e marcadores de consulta ficam em pane superior com eventos habilitados.",
            "Tracklogs, topologia, halos e pacotes animados ficam em pane inferior sem pointer-events.",
            "Reforça cursor e área clicável dos ícones de estação e objetos APRS.",
            "Build de validação somente para Windows x64 Portable.",
        ],
    },
    "1.7.11": {
        "title": "Validação Windows x64: correção do menu Itens do mapa",
        "items": [
            "Corrige o menu Itens do mapa que ficava recortado pela barra superior.",
            "O dropdown passa a ser posicionado como camada fixa abaixo do botão, fora do overflow da barra.",
            "Mantém abertura/fechamento por clique, fechamento ao clicar fora e reposicionamento em scroll/resize.",
            "Build de validação somente para Windows x64 Portable.",
        ],
    },
    "1.7.10": {
        "title": "Validação Windows x64: mapa unificado, APRS-IS animado e cliques restaurados",
        "items": [
            "A barra do Mapa passa a ter um único período para estações, objetos, tracklogs, enlaces e replay.",
            "Itens do mapa reúne toggles para estações, objetos, tracklogs, enlaces RF, enlaces iGate/APRS-IS e pacotes em movimento, todos ligados por padrão.",
            "O tipo de mapa pode ser trocado diretamente entre OSM, Topográfico e Satélite.",
            "A entrega do pacote ao APRS-IS é animada no próprio iGate, sem inventar uma coordenada geográfica para a Internet.",
            "Camadas de animação, tracklog e topologia deixam de capturar cliques, preservando a interação com estações e objetos.",
            "Build de validação somente para Windows x64 Portable.",
        ],
    },
    "1.7.9": {
        "title": "Validação Windows x64: velocidade da animação no Mapa e rótulo Versão",
        "items": [
            "Na barra contextual do Mapa, o controle Velocidade passa a ficar entre Topologia observada e o seletor de período.",
            "As opções de velocidade são 0,5x, 1x, 2x e 5x, com 1x como padrão.",
            "O seletor da barra do Mapa e o seletor do Replay permanecem sincronizados e controlam a mesma velocidade de animação.",
            "A velocidade escolhida fica persistida localmente para a próxima abertura.",
            "Na barra superior, o texto Build passa a ser exibido como Versão em português.",
            "Build de validação somente para Windows x64 Portable, destinado à validação dos ajustes recentes.",
        ],
    },
    "1.7.8": {
        "title": "Validação Windows x64: tráfego APRS hop a hop e ACK pelo path observado",
        "items": [
            "A animação de tráfego passa a percorrer os segmentos observados sequencialmente, hop a hop.",
            "Cada hop ativa visualmente a estação de destino quando o pacote chega ao nó.",
            "Enlaces RF permanecem distintos dos trechos APRS-IS/Internet, que continuam com representação própria.",
            "ACK/REJ e respostas correlacionadas usam o path observado no pacote de retorno; quando os mesmos digipeaters são usados, a animação volta pelo mesmo caminho em sentido inverso.",
            "Não é criado enlace direto artificial entre origem e destino quando existem hops observados.",
            "Respostas automáticas a queries APRS ficam ativadas por padrão em novas configurações.",
            "Build de validação solicitado somente para Windows x64 Portable, sem instalador e sem builds de outras plataformas.",
        ],
    },
    "1.7.7": {
        "title": "Mapa mais limpo, novos padrões visuais e checagem de atualização a cada 30 minutos",
        "items": [
            "O botão Histórico permanece somente na barra contextual do Mapa; o antigo botão global deixa de ser recriado pelo patch legado de build.",
            "Na aba Mensagens, a ação destrutiva passa a se chamar Limpar, mantendo destaque vermelho e confirmação antes da exclusão.",
            "A Topologia observada passa a usar amarelo (#ffff00) e espessura mínima de 1 px como padrão para novas configurações.",
            "O Tracklog permanece azul por padrão, e animações de atividade e som continuam ativados por padrão.",
            "A verificação periódica de nova versão passa de 5 para 30 minutos, sem sobrepor verificações ainda em andamento.",
            "Windows ARM64 passa a ter Setup e Portable nativos, e o atualizador escolhe automaticamente o pacote da arquitetura correta.",
            "A topologia passa a preservar a capitalização dos q-constructs APRS-IS, evitando interpretar qAr/links remotos de Internet como qAR/enlace RF.",
            "Preferências já personalizadas pelo usuário são preservadas; os novos valores visuais valem como padrão para instalações/configurações não personalizadas.",
            "Adicionados testes de regressão para evitar duplicação do Histórico, validar o botão Limpar, os padrões do Mapa e a nova cadência de atualização.",
            "Release completa para Windows x64 e ARM64, Linux x86_64, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.7.6": {
        "title": "Atualizador Windows reforçado, KML com Salvar como e novos rankings",
        "items": [
            "No Windows, a atualização automática passa a usar helper CMD nativo como caminho principal, reduzindo falhas de inicialização do PowerShell.",
            "O KML agora pergunta onde salvar o arquivo no desktop e usa seletor nativo de arquivo quando disponível.",
            "Os botões Histórico e Exportar KML foram movidos para a mesma barra contextual do Mapa, junto de Estações, Tracklog e Topologia.",
            "A aba Estatísticas ganha o ranking Estações que mais interagiram, considerando somente conversas APRS manuais e excluindo beacons, telemetria, ACK/REJ, queries, respostas automáticas, boletins e retries.",
            "A exportação KML continua com Estações, Posições, Tracklogs e Topologia selecionados por padrão e período configurável.",
            "Adicionados testes de regressão para o helper Windows, Salvar como do KML, posição dos controles no Mapa e ranking de conversas manuais.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.7.5": {
        "title": "Exportação KML, validação de posições e novas análises da rede",
        "items": [
            "Adicionada exportação KML pela barra superior, com Estações, Posições, Tracklogs e Topologia selecionados por padrão e período configurável.",
            "Posições 0,0, inválidas, saltos implausíveis e coordenadas incompatíveis com um iGate RF conhecido deixam de contaminar mapa, tracklogs, topologia, replay e exportações.",
            "A aba Estatísticas ganha os blocos Estações com problemas e Possíveis melhorias, com evidência/recorrência e atalhos para Mapa e Logs.",
            "Indicativos dos rankings Digipeaters mais utilizados e iGates mais ativos passam a abrir diretamente a estação no Mapa.",
            "Conversas da aba Mensagens podem ser ordenadas por Remetente ou Data, em ordem crescente/decrescente, e a ação Apagar todas remove somente o histórico local de mensagens após confirmação.",
            "Adicionados testes de regressão para validação geográfica, KML, navegação das Estatísticas e controles de Mensagens.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.7.4": {
        "title": "Erros do atualizador agora ficam visíveis no próprio modal",
        "items": [
            "Corrigida a camada visual das mensagens do atualizador: o toast agora fica acima do modal e não é mais desfocado pelo overlay.",
            "Falhas de download/instalação passam a ser exibidas também dentro do modal de atualização, em uma caixa destacada e legível.",
            "O estado do modal distingue claramente preparação, sucesso e erro, mantendo os botões disponíveis após uma falha.",
            "A mensagem técnica do backend permanece visível para diagnóstico, sem depender de um aviso temporário.",
            "Adicionados testes de regressão para z-index, mensagem inline e reativação dos controles após erro.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.7.3": {
        "title": "Atualizador reparado e ranking de clientes consolidado por família",
        "items": [
            "Corrigida a geração dos scripts auxiliares do atualizador: as quebras de linha agora são gravadas corretamente em PowerShell e Bash.",
            "O botão Baixar e instalar mostra feedback imediato, dispara diretamente o fluxo de atualização e registra as etapas no diagnóstico.",
            "O updater registra solicitação, asset, URL, caminho temporário, tamanho, SHA-256 e falhas para facilitar diagnóstico.",
            "Estatísticas passa a agrupar versões semânticas do mesmo cliente em uma única família, por exemplo Dire Wolf 1.7, 1.8 e 1.9 em Dire Wolf.",
            "Aliases, nomes originais e TOCALLs continuam preservados internamente para diagnóstico, enquanto a interface mostra o nome canônico consolidado.",
            "Adicionados testes de regressão que geram os helpers reais e validam a consolidação por família.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.7.2": {
        "title": "Mapa mais compacto, tempo relativo e estatísticas consolidadas",
        "items": [
            "Estações, Tracklog e Topologia observada passam para a mesma linha contextual do botão Histórico, liberando mais área vertical para o mapa.",
            "O popup da estação mostra o tempo decorrido desde a última recepção e o atualiza enquanto permanece aberto.",
            "O tempo relativo respeita Português, English, Español e Français, com formatos compactos para minutos, horas e dias.",
            "O ranking de software/dispositivos consolida TOCALLs diferentes que resolvem para o mesmo nome amigável, evitando linhas duplicadas.",
            "Os identificadores técnicos continuam preservados internamente e o destaque do PT2VHF APRS Client é mantido após a consolidação.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.7.1": {
        "title": "Atualizador corrigido, Mapa refinado e nova aba Sobre",
        "items": [
            "O atualizador só encerra a aplicação depois que o helper externo confirma que iniciou; falhas deixam a aplicação aberta.",
            "O indicador de nova versão pulsa e o modal permanece aberto durante o fluxo de atualização.",
            "Tracklogs rejeitam saltos irreais de coordenadas e quebram linhas históricas em relocações/extremos.",
            "Estações, Tracklog e Topologia ganham controles independentes de visibilidade e período; Atividade é removido.",
            "Histórico/Replay passa a aparecer abaixo das abas somente quando o Mapa está ativo.",
            "Mensagens sinaliza novas mensagens diretas na aba e Estações mais ativas ganha atalho clicável para mensagem rápida.",
            "Nova aba Sobre reúne autor, contatos, tiny.cc/aprs e divulgação manual por Announcement APRS.",
            "Revisadas e ampliadas as traduções PT/EN/ES/FR.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.7": {
        "title": "Nova linha 1.7: mensagens seguras, idiomas e interface refinada",
        "items": [
            "Os controles Atividade e Topologia observada ficam acima do mapa, sem cobrir o canvas.",
            "A animação de tráfego ao vivo vem ativada por padrão em novas instalações e pode ser desligada em Configurações.",
            "A conversa em foco e o campo Destinatário ficam sincronizados para reduzir o risco de envio à estação errada.",
            "Os filtros da aba Mensagens ficam mais compactos e com rótulos em uma única linha.",
            "A interface passa a oferecer Português, English, Español e Français.",
            "Estatísticas mostra somente nomes amigáveis dos aplicativos e ganha fonte maior com controle de tamanho em Configurações.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.6.24": {
        "title": "Logo APRS oficial única e consolidação visual",
        "items": [
            "A logo APRS enviada pelo projeto passa a ser a fonte visual única da aplicação.",
            "Cabeçalho, favicon, bandeja do Windows, ícones Windows/Linux/macOS e capa do Manual PDF passam a derivar do mesmo arquivo PNG oficial.",
            "O ícone do macOS deixa de ser desenhado por código e passa a ser gerado diretamente da logo oficial.",
            "As notas internas da v1.6.23 são incorporadas para manter o histórico de novidades coerente.",
            "O backlog é consolidado, removendo itens já concluídos e mantendo abertas somente as validações e melhorias ainda pendentes.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.6.23": {
        "title": "Identidade visual, filtro de atividade e legenda do mapa",
        "items": [
            "Padroniza a identidade visual da aplicação nos artefatos e documentação existentes.",
            "Adiciona no Mapa filtro por última interação: Tudo, menos de 2 h, 2 a 24 h e mais de 24 h.",
            "Marcadores, tracklogs e enlaces de estações conhecidas respeitam o filtro de atividade.",
            "A legenda do Mapa pode ser minimizada ou expandida e preserva a preferência local.",
            "Corrige o rate-limit para permitir corretamente a primeira resposta automática a query APRS após a inicialização.",
            "Release completa multiplataforma.",
        ],
    },
    "1.6.22": {
        "title": "Atualização integrada por plataforma",
        "items": [
            "Clicar em Nova versão passa a baixar e instalar automaticamente o pacote correto da plataforma e arquitetura em uso.",
            "O download é feito somente da Release oficial e é validado por tamanho e SHA-256 antes da instalação.",
            "Um updater auxiliar encerra a instância anterior, força somente o PID correto após timeout quando necessário, instala/substitui e abre a nova versão.",
            "Windows Portable mantém backup para rollback; Windows Setup executa o instalador correspondente.",
            "Linux AppImage/DEB/TAR.GZ e macOS DMG recebem fluxos próprios de atualização e relançamento.",
            "Um lock com PID impede atualizações concorrentes entre instâncias e se recupera de locks obsoletos após crash.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.6.21": {
        "title": "Estatísticas da rede e ranking de estações ativas",
        "items": [
            "A aba Análise passa a se chamar Estatísticas em toda a interface e documentação.",
            "A nova seção Estações mais ativas ordena o tráfego útil por indicativo no período selecionado.",
            "Pacotes de telemetria são excluídos do ranking para evitar distorção por transmissões automáticas frequentes.",
            "iGates e digipeaters também são excluídos do ranking principal e permanecem nas estatísticas dedicadas.",
            "O ranking exibe posição, indicativo, pacotes válidos e percentual sobre o total considerado.",
            "Release de teste somente Windows x64 Portable.",
        ],
    },
    "1.6.20": {
        "title": "Nomes amigáveis APRS, ranking do cliente, idioma compacto e RF correto",
        "items": [
            "A aba Análise passa a resolver TOCALLs para nomes amigáveis de software/dispositivo usando um snapshot local da base APRS Device Identification.",
            "O ranking mostra os Top 20 e, se o PT2VHF APRS Client estiver fora do corte, acrescenta sua posição real, quantidade e percentual em uma linha destacada.",
            "O PT2VHF APRS Client passa a transmitir o identificador experimental APZVHF para permitir medir sua adoção sem depender do TOCALL genérico APRS.",
            "O seletor de idioma no topo passa a mostrar somente o idioma atual e abre um menu com Português/Brasil e English/Inglaterra.",
            "Corrige enlaces qAR/qAO até o IGate: quando o caminho é RF, a linha permanece contínua e o IGate fica apenas como metadado do enlace.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.6.19": {
        "title": "Análise de clientes, respostas de queries e idioma no topo",
        "items": [
            "A aba Análise passa a mostrar clientes/versões APRS detectados pelo TOCALL do último pacote de cada estação, em ordem do mais usado para o menos usado.",
            "O popup da estação passa a exibir uma área clara e persistente com o resultado da última query, incluindo status, RTT, resposta e caminho do Trace quando disponível.",
            "Adiciona histórico de queries por estação diretamente no popup do Mapa.",
            "Ao reabrir o popup, a última query registrada daquela estação é recuperada do banco local.",
            "Restaura o controle rápido de idioma no topo, com Português/Brasil e English/Inglaterra, preservando a escolha do usuário.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.6.18": {
        "title": "Queries APRS, Ping/ACK e Trace no mapa",
        "items": [
            "Adiciona consultas APRS direcionadas de posição, status, estações ouvidas e trace diretamente pelo popup do mapa.",
            "Adiciona Ping/ACK com medição de RTT e timeout.",
            "O Trace recebido é interpretado e desenhado no mapa somente nos hops com posição conhecida, sem inventar localização para nós desconhecidos.",
            "Adiciona histórico local das queries, respostas e tempos de resposta.",
            "Prepara o cliente para responder automaticamente a queries APRS de posição, status e trace, com opção em Configurações e rate-limit.",
            "Release completa para Windows, Linux, macOS e Manual PDF.",
        ],
    },
    "1.6.17": {
        "title": "Release completa multiplataforma com correções de estabilidade",
        "items": [
            "Consolida as correções de CPU e travamento introduzidas nas versões 1.6.13 a 1.6.16.",
            "Mantém o pipeline RX otimizado, o refresh de mapa single-flight e a consulta de topologia indexada com proteção de timeout.",
            "Mantém os indicadores de CPU e RAM em tempo real na barra superior para diagnóstico operacional.",
            "Publica Windows x64 Setup + Portable, Linux x86_64 TAR.GZ/AppImage/DEB, macOS ARM64/Intel e Manual PDF versionado.",
            "O manual é regenerado com screenshots da própria versão e validado no workflow antes da publicação.",
        ],
    },
    "1.6.16": {
        "title": "Correção da consulta de topologia que saturava o backend",
        "items": [
            "Remove UPPER() dos JOINs de topologia para permitir lookup indexado pelo callsign.",
            "Impede consultas /api/topology concorrentes com coalescência/cache curto.",
            "Adiciona limite interno de tempo à consulta para que nenhum worker fique preso por minutos.",
            "Adiciona single-flight ao carregamento de topologia no frontend.",
            "Inclui índices auxiliares de topologia para bancos existentes e novos.",
            "Release de teste somente Windows x64 Portable, sem instalador e sem documentação.",
        ],
    },
    "1.6.15": {
        "title": "Correção do fan-out do Mapa e medidores de recursos",
        "items": [
            "Remove o refresh completo do mapa disparado por cada estação sem marcador.",
            "Impede execuções simultâneas de loadMapData com trava single-flight.",
            "Limita animações ao vivo e deduplica indicadores visuais por estação em cada ciclo.",
            "Adiciona indicadores de CPU e RAM em tempo real na barra superior.",
            "CPU/RAM somam o processo principal e processos filhos do WebView2.",
            "Release de teste somente Windows x64 Portable, sem instalador e sem documentação.",
        ],
    },
    "1.6.14": {
        "title": "RX em transação única",
        "items": [
            "Consolida o processamento de cada pacote APRS recebido em uma única transação SQLite.",
            "Log RX, histórico de pacotes, topologia e estação/track deixam de abrir conexões e commits independentes por pacote.",
            "Mantém o housekeeping em lotes introduzido na v1.6.13.",
            "Registra transações RX lentas no diagnóstico para identificar gargalos residuais.",
            "Objetivo principal: reduzir CPU, contenção do banco e starvation das rotas HTTP.",
            "Release de teste somente Windows x64 Portable, sem instalador e sem documentação.",
        ],
    },
    "1.6.13": {
        "title": "Redução de CPU e housekeeping SQLite",
        "items": [
            "Remove as limpezas de tabelas grandes executadas a cada pacote APRS recebido.",
            "Housekeeping de packets, aprs_log e topology_events passa a ocorrer em lotes a cada 1.000 registros ou 5 minutos.",
            "A remoção do histórico excedente passa a usar corte por chave primária, evitando varreduras completas repetidas.",
            "Reduz a frequência de pollings pesados e atualiza mapa, mensagens, estações e log principalmente quando a aba correspondente está ativa.",
            "Mantém a instrumentação diagnóstica da v1.6.12 para acompanhar eventuais travamentos residuais.",
            "Release de teste somente Windows x64 Portable, sem instalador e sem documentação.",
        ],
    },
    "1.6.12": {
        "title": "Portable de diagnóstico do travamento",
        "items": [
            "Instrumenta cada request do backend local com endpoint, thread, duração e quantidade de requests ativos.",
            "Watchdog interno testa o servidor local e gera dump de todas as threads após falhas consecutivas ou saturação.",
            "Operações SQLite acima de 750 ms e erros de banco passam a ser registrados no diagnóstico.",
            "O log persistente fica na pasta de dados como diagnostics.log e pode ser baixado por /api/diagnostics/log.",
            "A mensagem de timeout informa qual endpoint deixou de responder.",
            "Release de diagnóstico somente Windows x64 Portable, sem instalador e sem documentação.",
        ],
    },
    "1.6.11": {
        "title": "Teste de estabilidade do Portable",
        "items": [
            "Remove PRAGMA journal_mode=WAL do caminho de cada request e deixa a configuração WAL somente na inicialização.",
            "Mensagens multipartes passam a ser registradas em uma única transação SQLite.",
            "Pollings da interface deixam de se sobrepor quando uma chamada demora.",
            "Chamadas ao backend local ganham timeout de 10 segundos em vez de permanecer indefinidamente presas.",
            "Após enfileirar uma mensagem, o botão Enviar é liberado sem aguardar a recarga da lista.",
            "Release de teste somente Windows x64 Portable, sem instalador e sem documentação.",
        ],
    },
    "1.6.10": {
        "title": "Release completa multiplataforma",
        "items": [
            "Consolida a correção do envio de mensagens com fila assíncrona e deduplicação.",
            "Mantém a rotina segura de encerramento e manutenção leve do SQLite.",
            "Corrige definitivamente o pipeline do ícone Windows usando a identidade visual estável.",
            "Aplica todos os patches acumulados também aos builds macOS e à geração do manual.",
            "Publica Windows Setup e Portable, Linux TAR.GZ/AppImage/DEB, macOS ARM64/Intel e Manual PDF.",
        ],
    },
    "1.6.9": {
        "title": "Estabilidade de mensagens e build",
        "items": [
            "Mantidas as correções de fila assíncrona e deduplicação no envio de mensagens.",
            "Mantida a rotina de encerramento e manutenção leve do SQLite.",
            "Corrigido o teste legado de identidade visual que impedia os builds Windows e Linux.",
            "O build usa temporariamente a logo estável anterior até a logo oficial ser reintegrada com arquivo validado.",
            "Release para Windows x64 e Linux x86_64, sem macOS e sem PDF.",
        ],
    },
    "1.6.8": {
        "title": "Fila de transmissão e estabilidade",
        "items": [
            "Envio de mensagens passa a usar fila assíncrona no backend, evitando travamento da interface.",
            "Cliques repetidos na mesma mensagem em poucos segundos são deduplicados.",
            "O botão Enviar fica bloqueado enquanto a solicitação é registrada.",
            "Falhas de socket deixam de prender a requisição web e passam a acionar recuperação da conexão.",
            "Ao encerrar, a aplicação cancela filas pendentes e executa manutenção leve do SQLite.",
            "Release para Windows x64 e Linux x86_64, sem macOS e sem PDF.",
        ],
    },
    "1.6.7": {
        "title": "Primeira release Linux atualizada",
        "items": [
            "Build Linux x86_64 com pacote TAR.GZ, AppImage e DEB.",
            "Aplicadas no Linux as correções acumuladas das versões 1.6.4 a 1.6.6.",
            "A logo APRS oficial é usada na interface e no ícone dos pacotes Linux.",
            "Incluídos testes smoke em Ubuntu 22.04 e 24.04.",
            "Release somente Linux, sem Windows, macOS ou PDF.",
        ],
    },
    "1.6.6": {
        "title": "Configuração, manutenção e identidade visual",
        "items": [
            "Corrigido o salvamento da aba Configuração e o fluxo Salvar e sair.",
            "Seletor de idioma passa a exibir bandeiras reais do Brasil e dos EUA no Windows.",
            "Adicionado Limpar tudo com destaque e confirmação dupla, preservando configuração e favoritos.",
            "A logo APRS fornecida passa a ser usada na aplicação e como base do ícone Windows.",
            "Release somente Windows x64, sem PDF.",
        ],
    },
    "1.6.5": {
        "title": "Manutenção e notificações",
        "items": [
            "Novo bloco Manutenção centraliza as ações de limpeza do banco.",
            "Notificações do navegador agora têm volume, seleção de som e botão de teste.",
            "A barra de histórico/replay do Mapa fica oculta por padrão e pode ser aberta pelo cabeçalho.",
            "Corrigido o envio para destinatários com sufixo alfanumérico, incluindo PY2OFU-D.",
            "Release somente Windows x64, sem PDF.",
        ],
    },
    "1.6.4": {
        "title": "Correções de Mensagens e Replay",
        "items": [
            "Corrigido o envio de mensagens pelo botão Enviar e pela tecla Enter.",
            "Corrigido o filtro por origem na aba Mensagens.",
            "Replay volta a mostrar os pacotes trafegando entre os nós, com rastro visual.",
            "Estações móveis continuam deixando tracklog progressivo durante o replay.",
            "Incluído teste de regressão para evitar replay apenas com highlight das estações.",
            "Release somente Windows x64 Portable.",
        ],
    },
    "1.6.3": {
        "title": "Replay móvel e seleção rápida de período",
        "items": [
            "Seleção rápida do replay: 1 h, 12 h, 24 h, 7 dias ou todo o histórico.",
            "Removidos os campos manuais De/Até e compactada a área de período.",
            "Estações móveis agora se deslocam durante o replay e deixam o tracklog progressivamente.",
            "Build desta versão restrito ao Windows x64, sem geração de PDF.",
        ],
    },
    "1.6.2": {
        "title": "Replay da Rede e melhorias de estabilidade",
        "items": [
            "Replay da Rede com linha do tempo, seek e velocidades de 0,25x a 20x.",
            "Controles de animação movidos para a parte inferior do Mapa.",
            "Som e animação de atividade limitados às estações visíveis no enquadramento atual.",
            "Indicador RX/TX de atividade na barra superior.",
            "Legenda do Mapa sincronizada com cores e espessuras configuradas.",
            "Correção da espessura da topologia e salvamento centralizado no rodapé da Configuração.",
            "Auto-update removido: o cliente apenas informa quando há uma nova versão.",
            "Verificação de versão com timeout e recuperação automática após falhas.",
            "Botão Ver logs no popup da estação.",
        ],
    },
}


def notes_for(version: str) -> dict[str, Any]:
    data = VERSION_NOTES.get(str(version or "").strip(), {})
    return {
        "version": str(version or "").strip(),
        "title": str(data.get("title") or ""),
        "items": list(data.get("items") or []),
    }
